<?php
namespace App\Services;
use App\Models\{Category,Customer,Order,Product,ProductImage,ProductVariant,WooCommerceImportMap,WooCommerceImportRun};
use Illuminate\Support\Facades\{DB,Hash,Http,Storage};
use Illuminate\Support\Str;
class WooCommerceImporter {
 private string $base; private string $key; private string $secret; private WooCommerceImportRun $run; private array $stats=[];
 public function run(WooCommerceImportRun $run,string $key,string $secret): WooCommerceImportRun {
  $this->run=$run; $this->base=rtrim((string)$run->source_url,'/').'/wp-json/wc/v3'; $this->key=$key;$this->secret=$secret;
  $this->stats=['categories'=>0,'products'=>0,'variants'=>0,'customers'=>0,'orders'=>0,'media'=>0,'skipped'=>0,'errors'=>0];
  $run->update(['status'=>'running','started_at'=>now(),'finished_at'=>null,'last_error'=>null,'summary'=>$this->stats]);
  try { $o=$run->options?:[]; if(!empty($o['categories']))$this->categories(); if(!empty($o['products']))$this->products(!empty($o['media'])); if(!empty($o['customers']))$this->customers(); if(!empty($o['orders']))$this->orders(); $run->update(['status'=>'completed','summary'=>$this->stats,'finished_at'=>now()]); }
  catch(\Throwable $e){$this->stats['errors']++;$run->update(['status'=>'failed','summary'=>$this->stats,'last_error'=>Str::limit($e->getMessage(),60000,''),'finished_at'=>now()]);throw $e;}
  return $run->fresh();
 }
 private function pages(string $endpoint, callable $fn,array $params=[]): void { for($page=1;;$page++){ $r=$this->get($endpoint,array_merge(['per_page'=>50,'page'=>$page],$params)); $rows=$r->json(); if(!is_array($rows)||!count($rows))break; foreach($rows as $row){try{$fn($row);}catch(\Throwable $e){$this->stats['errors']++;$this->map($endpoint,(int)($row['id']??0),null,'error',Str::limit($e->getMessage(),2000,''));}} if(count($rows)<50)break; } }
 private function get(string $endpoint,array $query=[]){$r=Http::withBasicAuth($this->key,$this->secret)->acceptJson()->timeout(45)->retry(2,500)->get($this->base.'/'.ltrim($endpoint,'/'),$query);$r->throw();return $r;}
 private function categories():void{$this->pages('products/categories',function($w){$c=Category::updateOrCreate(['slug'=>$this->slug($w['slug']??$w['name']??'category-'.$w['id'])],['name'=>$w['name']??'Category','description'=>strip_tags($w['description']??''),'is_active'=>true,'sort_order'=>(int)($w['menu_order']??0)]);$this->map('category',(int)$w['id'],$c->id);$this->stats['categories']++;});}
 private function products(bool $media):void{$this->pages('products',function($w)use($media){DB::transaction(function()use($w,$media){$categoryId=null;foreach(($w['categories']??[]) as $wc){$categoryId=$this->mappedLocal('category',(int)$wc['id'])?:Category::where('slug',$this->slug($wc['slug']??$wc['name']))->value('id');if($categoryId)break;}$status=in_array($w['status']??'',['publish','private'],true)?'active':'draft';$price=(float)($w['price']!==''?($w['price']??0):($w['regular_price']??0));$p=Product::updateOrCreate(['slug'=>$this->slug($w['slug']??$w['name'].'-'.$w['id'])],['category_id'=>$categoryId,'name'=>$w['name']??'Imported product','subtitle'=>null,'description'=>$this->clean($w['description']??''),'story'=>$this->clean($w['short_description']??''),'status'=>$status,'is_featured'=>(bool)($w['featured']??false),'base_price'=>$price,'compare_at_price'=>$this->compare($w),'stock'=>(int)($w['stock_quantity']??0),'sku'=>blank($w['sku']??null)?null:$w['sku'],'meta_title'=>$w['name']??null,'meta_description'=>Str::limit(strip_tags($w['short_description']??''),500,'')]);$this->map('product',(int)$w['id'],$p->id);$this->stats['products']++;if(($w['type']??'')==='variable')$this->variations($w,$p);if($media)$this->images($w,$p);});});}
 private function variations(array $w,Product $p):void{$ids=$w['variations']??[];foreach(array_chunk($ids,50) as $chunk){foreach($chunk as $id){try{$v=$this->get('products/'.$w['id'].'/variations/'.$id)->json();$attrs=collect($v['attributes']??[])->pluck('option')->filter()->implode(' / ');$sku=blank($v['sku']??null)?('WC-'.$w['id'].'-'.$id):$v['sku'];$local=ProductVariant::updateOrCreate(['sku'=>$sku],['product_id'=>$p->id,'name'=>$attrs?:'Variant','size_label'=>$attrs?:null,'price'=>(float)($v['price']??$v['regular_price']??$p->base_price),'compare_at_price'=>$this->compare($v),'stock'=>(int)($v['stock_quantity']??0),'is_active'=>($v['status']??'publish')==='publish','sort_order'=>(int)($v['menu_order']??0)]);$this->map('variant',(int)$id,$local->id);$this->stats['variants']++;}catch(\Throwable $e){$this->stats['errors']++;$this->map('variant',(int)$id,null,'error',$e->getMessage());}}}}
 private function images(array $w,Product $p):void{foreach(($w['images']??[]) as $i=>$img){$src=$img['src']??null;$sourceId=(int)($img['id']??0);if(!$src)continue;if($sourceId && $this->mappedLocal('media',$sourceId)){ $this->stats['skipped']++; continue; }try{$ext=pathinfo(parse_url($src,PHP_URL_PATH)?:'',PATHINFO_EXTENSION)?:'jpg';$path='products/imported/'.$p->id.'/'.Str::uuid().'.'.preg_replace('/[^a-z0-9]/i','',$ext);$res=Http::timeout(30)->retry(2,400)->get($src);$res->throw();Storage::disk('public')->put($path,$res->body());ProductImage::updateOrCreate(['product_id'=>$p->id,'path'=>$path],['alt_text'=>$img['alt']??$p->name,'sort_order'=>$i,'is_primary'=>$i===0]);$this->stats['media']++;if($sourceId)$this->map('media',$sourceId,$p->id);}catch(\Throwable $e){$this->stats['errors']++;if($sourceId)$this->map('media',$sourceId,null,'error',$e->getMessage());}}}
 private function customers():void{$this->pages('customers',function($w){$email=strtolower(trim((string)($w['email']??'')));if(!$email){$this->stats['skipped']++;return;}$c=Customer::updateOrCreate(['email'=>$email],['first_name'=>$w['first_name']?:'Customer','last_name'=>$w['last_name']??null,'phone'=>$w['billing']['phone']??null,'company'=>$w['billing']['company']??null,'address'=>$w['billing']??null,'marketing_opt_in'=>false,'is_active'=>true]);if(!$c->password){$c->password=Hash::make(Str::random(48));$c->save();}$this->map('customer',(int)$w['id'],$c->id);$this->stats['customers']++;});}
 private function orders():void{$this->pages('orders',function($w){DB::transaction(function()use($w){$customer=$this->mappedLocal('customer',(int)($w['customer_id']??0));if(!$customer&&!empty($w['billing']['email']))$customer=Customer::where('email',strtolower($w['billing']['email']))->value('id');$status=['on-hold'=>'pending','pending'=>'pending','processing'=>'processing','completed'=>'delivered','cancelled'=>'cancelled','refunded'=>'refunded','failed'=>'cancelled'][$w['status']??'pending']??'pending';$pay=($w['date_paid']??null)?'paid':(($w['status']??'')==='failed'?'failed':'pending');$num='WC-'.($w['number']??$w['id']);$o=Order::updateOrCreate(['order_number'=>$num],['customer_id'=>$customer,'status'=>$status,'payment_status'=>$pay,'currency'=>$w['currency']??'PKR','subtotal'=>(float)($w['total']??0)-(float)($w['shipping_total']??0)+(float)($w['discount_total']??0),'discount_total'=>(float)($w['discount_total']??0),'shipping_total'=>(float)($w['shipping_total']??0),'grand_total'=>(float)($w['total']??0),'customer_name'=>trim(($w['billing']['first_name']??'').' '.($w['billing']['last_name']??'')),'customer_email'=>$w['billing']['email']??null,'customer_phone'=>$w['billing']['phone']??null,'shipping_address'=>$w['shipping']??null,'billing_address'=>$w['billing']??null,'payment_method'=>$w['payment_method']??null,'shipping_method'=>collect($w['shipping_lines']??[])->pluck('method_title')->implode(', '),'notes'=>$w['customer_note']??null,'placed_at'=>$w['date_created']??now(),'fulfilled_at'=>$status==='delivered'?($w['date_completed']??now()):null]);$o->items()->delete();foreach(($w['line_items']??[]) as $li){$pid=$this->mappedLocal('product',(int)($li['product_id']??0));$vid=$this->mappedLocal('variant',(int)($li['variation_id']??0));$qty=max(1,(int)($li['quantity']??1));$o->items()->create(['product_id'=>$pid,'product_variant_id'=>$vid,'product_name'=>$li['name']??'Imported item','sku'=>$li['sku']??null,'quantity'=>$qty,'unit_price'=>$qty?((float)($li['total']??0)/$qty):0,'line_total'=>(float)($li['total']??0)]);}$this->map('order',(int)$w['id'],$o->id);$this->stats['orders']++;});});}
 private function map(string $type,int $source,?int $local,string $status='imported',?string $message=null):void{if(!$source)return;WooCommerceImportMap::updateOrCreate(['run_id'=>$this->run->id,'entity_type'=>$type,'source_id'=>$source],['local_id'=>$local,'status'=>$status,'message'=>Str::limit((string)$message,2000,'')?:null]);}
 private function mappedLocal(string $type,int $source):?int{if(!$source)return null;return WooCommerceImportMap::where('entity_type',$type)->where('source_id',$source)->whereHas('run',fn($q)=>$q->where('source_url',$this->run->source_url))->whereNotNull('local_id')->latest('id')->value('local_id');}
 private function slug(string $s):string{return Str::slug($s)?:'imported-'.Str::random(8);} private function clean(string $s):string{$text=html_entity_decode(strip_tags($s),ENT_QUOTES|ENT_HTML5,'UTF-8');$text=preg_replace('/\s+/u',' ',$text);return trim((string)$text);} private function compare(array $w):?float{$r=(float)($w['regular_price']??0);$s=(float)($w['sale_price']??0);return $s>0&&$r>$s?$r:null;}
}
