@extends('admin.layouts.app')
@section('title','Media')
@section('header','Media Library')
@section('eyebrow','CMS / assets')
@section('content')
<div style="display:flex;align-items:flex-end;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:18px"><div><h2 style="font-size:27px;margin:0">Media library</h2><p class="admin-muted" style="font-size:12px;margin:7px 0 0">{{ number_format($summary['all']) }} assets · {{ number_format($summary['images']) }} images · {{ number_format($summary['bytes']/1048576,1) }} MB recorded</p></div></div>
<section class="admin-card" style="padding:14px;margin-bottom:14px"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.media.store') }}" style="display:grid;grid-template-columns:1fr 1fr auto;gap:8px">@csrf<input class="admin-field" type="file" name="files[]" multiple required><input class="admin-field" name="alt_text" placeholder="Shared alt text (optional)"><button class="admin-btn admin-btn-primary">Upload media</button></form></section>
<section class="admin-card"><form method="GET" style="display:grid;grid-template-columns:1fr 170px auto;gap:8px;padding:14px;border-bottom:1px solid #e4e7ec"><input class="admin-field" name="q" value="{{ request('q') }}" placeholder="Search filename, alt text, caption"><select class="admin-field" name="type"><option value="">All files</option><option value="image" @selected(request('type')==='image')>Images</option><option value="other" @selected(request('type')==='other')>Other files</option></select><button class="admin-btn">Filter</button></form>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;padding:14px">@forelse($assets as $a)<article style="border:1px solid #e4e7ec;border-radius:11px;overflow:hidden;background:#fff"><div style="aspect-ratio:4/3;background:#f5f6f8;display:grid;place-items:center;overflow:hidden">@if(str_starts_with($a->mime_type??'','image/'))<img src="{{ route('store.media',['path'=>$a->path]) }}" alt="{{ $a->alt_text }}" style="width:100%;height:100%;object-fit:cover">@else<span class="admin-muted" style="font-size:10px">{{ $a->mime_type ?: 'FILE' }}</span>@endif</div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.media.update',$a) }}" style="padding:12px;display:grid;gap:7px">@csrf @method('PUT')<input class="admin-field" name="name" value="{{ $a->name }}"><input class="admin-field" name="alt_text" value="{{ $a->alt_text }}" placeholder="Alt text"><input class="admin-field" name="caption" value="{{ $a->caption }}" placeholder="Caption"><input class="admin-field" type="file" name="replacement"><div class="admin-muted" style="font-size:8px;word-break:break-all">{{ $a->path }}</div><button class="admin-btn">Save metadata</button></form><form method="POST" action="{{ route('admin.media.destroy',$a) }}" style="padding:0 12px 12px">@csrf @method('DELETE')<button class="admin-btn" style="width:100%;color:#9d2018" data-admin-confirm="Delete this media file permanently?">Delete</button></form></article>@empty<div class="admin-muted" style="grid-column:1/-1;padding:45px;text-align:center">No media found.</div>@endforelse</div></section>
<div style="margin-top:18px">{{ $assets->links() }}</div>
<style>@media(max-width:1100px){.admin-card>div[style*="repeat(4"]{grid-template-columns:repeat(3,minmax(0,1fr))!important}}@media(max-width:800px){.admin-card>div[style*="repeat(4"]{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:520px){.admin-card>div[style*="repeat(4"]{grid-template-columns:1fr!important}}</style>
@endsection
