@extends('admin.layouts.app')
@section('title','Admin Users') @section('header','Admin Users') @section('eyebrow','System / access control')
@section('content')
<div style="margin-bottom:18px"><h2 style="font-size:27px;margin:0">Admin users & roles</h2><p class="admin-muted" style="font-size:12px;margin:7px 0 0">Least-privilege access, account lifecycle and password security.</p></div>
@if(!auth()->user()->isSuperAdmin())<div class="admin-alert admin-alert-danger">Only a Super Admin can create or modify admin accounts.</div>@endif
<div style="display:grid;grid-template-columns:minmax(0,1.35fr) minmax(320px,.65fr);gap:14px;align-items:start">
<section class="admin-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>User</th><th>Role</th><th>Last login</th><th>Status</th><th style="text-align:right">Actions</th></tr></thead><tbody>@foreach($users as $u)<tr><td><strong>{{ $u->name }}</strong><div class="admin-muted" style="font-size:9px;margin-top:4px">{{ $u->email }}</div></td><td>{{ $roles[$u->role]??str_replace('_',' ',ucfirst($u->role)) }}</td><td>{{ optional($u->last_login_at)->format('d M Y H:i') ?: 'Never' }}</td><td><span class="admin-status {{ $u->is_active?'success':'warning' }}">{{ $u->is_active?'Active':'Inactive' }}</span></td><td style="text-align:right">@if(auth()->user()->isSuperAdmin())<details style="display:inline-block;text-align:left"><summary class="admin-btn" style="cursor:pointer">Manage</summary><div class="admin-card" style="position:absolute;right:30px;z-index:20;width:310px;padding:14px;margin-top:6px"><form method="POST" action="{{ route('admin.admin-users.update',$u) }}">@csrf @method('PUT')<div style="display:grid;gap:8px"><input class="admin-field" name="name" value="{{ $u->name }}"><input class="admin-field" name="email" type="email" value="{{ $u->email }}"><select class="admin-field" name="role">@foreach($roles as $key=>$label)<option value="{{ $key }}" @selected($u->role===$key)>{{ $label }}</option>@endforeach</select><button class="admin-btn admin-btn-primary">Save user</button></div></form><div style="display:flex;gap:6px;margin-top:8px"><form method="POST" action="{{ route('admin.admin-users.reset',$u) }}">@csrf<button class="admin-btn">Reset password</button></form><form method="POST" action="{{ route('admin.admin-users.toggle',$u) }}">@csrf<button class="admin-btn">{{ $u->is_active?'Deactivate':'Activate' }}</button></form></div>@if($u->id!==auth()->id())<form method="POST" action="{{ route('admin.admin-users.destroy',$u) }}" style="margin-top:8px">@csrf @method('DELETE')<button class="admin-btn" style="width:100%;color:#9d2018" data-admin-confirm="Delete this admin user permanently?">Delete user</button></form>@endif</div></details>@endif</td></tr>@endforeach</tbody></table></div></section>
<aside class="admin-card" style="padding:20px;position:sticky;top:96px"><div class="admin-eyebrow">Create admin</div><p class="admin-muted" style="font-size:10px;line-height:1.6">A password setup/reset email is sent after account creation.</p><form method="POST" action="{{ route('admin.admin-users.store') }}" style="display:grid;gap:9px;margin-top:14px">@csrf<input class="admin-field" name="name" required placeholder="Full name"><input class="admin-field" name="email" type="email" required placeholder="Email"><input class="admin-field" name="password" type="password" minlength="12" required placeholder="Temporary password (12+ chars)"><select class="admin-field" name="role">@foreach($roles as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select><button class="admin-btn admin-btn-primary" @disabled(!auth()->user()->isSuperAdmin())>Create admin</button></form></aside></div>
<style>@media(max-width:900px){.admin-page>div:nth-child(3){grid-template-columns:1fr!important}.admin-page aside{position:static!important}}</style>
@endsection
