@extends('admin.layouts.app')
@section('title','Settings') @section('header','Store Settings') @section('eyebrow','System / configuration')
@section('content')
<div style="display:grid;grid-template-columns:minmax(0,1.2fr) minmax(340px,.8fr);gap:14px;align-items:start">
<form method="POST" action="{{ route('admin.settings.update') }}" class="admin-card" style="padding:20px">@csrf @method('PUT')<div class="admin-eyebrow">Store configuration</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px">
@foreach(['store_name'=>'Store name','currency'=>'Currency','support_email'=>'Support email','support_phone'=>'Support phone','order_prefix'=>'Order prefix','store_tagline'=>'Store tagline','instagram_url'=>'Instagram URL','facebook_url'=>'Facebook URL','tiktok_url'=>'TikTok URL','gift_wrap_fee'=>'Gift wrapping fee (PKR)'] as $k=>$label)<label style="font-size:11px;font-weight:680;{{ in_array($k,['store_tagline','instagram_url','facebook_url','tiktok_url'])?'grid-column:1/-1':'' }}">{{ $label }}<input class="admin-field" style="margin-top:7px" name="{{ $k }}" value="{{ old($k,$settings[$k]??($k==='currency'?'PKR':($k==='store_name'?'Scents by Aamir':''))) }}"></label>@endforeach
</div><button class="admin-btn admin-btn-primary" style="margin-top:16px">Save settings</button></form>
<aside style="display:grid;gap:14px"><section class="admin-card" style="padding:20px"><div class="admin-eyebrow">Transactional email</div><h3 style="font-size:16px;margin:7px 0 14px">Environment-controlled</h3>@foreach([['Mailer',$mail['mailer']],['SMTP host',$mail['host']],['SMTP port',$mail['port']],['SMTP username',$mail['username']],['From',$mail['from']],['Order alerts',$mail['order_notification']]] as [$l,$v])<div class="admin-mini-stat"><span class="admin-muted" style="font-size:10px">{{ $l }}</span><strong style="font-size:10px;word-break:break-all">{{ $v ?: 'Not configured' }}</strong></div>@endforeach<p class="admin-muted" style="font-size:9px;line-height:1.55;margin-top:14px">SMTP passwords remain in server `.env` and are intentionally never editable or displayed here.</p><a class="admin-btn" style="width:100%;box-sizing:border-box;margin-top:10px" href="{{ route('admin.mail-diagnostics.index') }}">Mail diagnostics</a></section></aside>
</div><style>@media(max-width:900px){.admin-page>div:first-child{grid-template-columns:1fr!important}}</style>
@endsection
