@extends('admin.layouts.app')
@section('title','Content')
@section('header','Content')
@section('eyebrow','CMS / publishing center')
@section('content')
<div style="display:flex;align-items:flex-end;justify-content:space-between;gap:15px;flex-wrap:wrap;margin-bottom:18px"><div><h2 style="font-size:27px;margin:0">Content operations</h2><p class="admin-muted" style="font-size:12px;margin:7px 0 0">Pages, editorial, navigation and media in one publishing workspace.</p></div><div style="display:flex;gap:8px"><a class="admin-btn" href="{{ route('admin.media.index') }}">Media library</a><a class="admin-btn admin-btn-primary" href="{{ route('admin.pages.create') }}">+ New page</a></div></div>
<div class="admin-kpi-grid" style="margin-bottom:14px">@foreach([['Pages',$stats['pages'],$stats['published_pages'].' published'],['Journal',$stats['journal'],$stats['published_journal'].' published'],['Media',$stats['media'],'assets'],['Navigations',$stats['navigations'],'menus']] as [$l,$v,$h])<div class="admin-card admin-kpi"><div class="admin-eyebrow">{{ $l }}</div><div class="admin-kpi-value">{{ $v }}</div><div class="admin-muted" style="font-size:10px">{{ $h }}</div></div>@endforeach</div>
<div class="admin-section-grid"><section class="admin-card"><div class="admin-card-header"><div><div class="admin-eyebrow">Pages</div><div style="font-size:14px;font-weight:700;margin-top:4px">Recently edited</div></div><a class="admin-btn" href="{{ route('admin.pages.index') }}">All pages</a></div>@foreach($recentPages as $p)<a href="{{ route('admin.pages.edit',$p) }}" style="display:flex;justify-content:space-between;gap:15px;padding:14px 18px;border-bottom:1px solid #edf0f3"><span style="font-size:11px;font-weight:700">{{ $p->title }}<span class="admin-muted" style="display:block;font-size:9px;margin-top:4px">/{{ $p->slug }}</span></span><span class="admin-status {{ $p->status==='published'?'success':'warning' }}">{{ ucfirst($p->status) }}</span></a>@endforeach</section>
<section class="admin-card"><div class="admin-card-header"><div><div class="admin-eyebrow">Journal</div><div style="font-size:14px;font-weight:700;margin-top:4px">Recently edited</div></div><a class="admin-btn" href="{{ route('admin.journal-posts.index') }}">All posts</a></div>@foreach($recentPosts as $p)<a href="{{ route('admin.journal-posts.edit',$p) }}" style="display:flex;justify-content:space-between;gap:15px;padding:14px 18px;border-bottom:1px solid #edf0f3"><span style="font-size:11px;font-weight:700">{{ $p->title }}<span class="admin-muted" style="display:block;font-size:9px;margin-top:4px">{{ $p->eyebrow ?: 'Editorial' }}</span></span><span class="admin-status {{ $p->status==='published'?'success':'warning' }}">{{ ucfirst($p->status) }}</span></a>@endforeach</section></div>
<section class="admin-card" style="margin-top:14px"><div class="admin-card-header"><div><div class="admin-eyebrow">Media</div><div style="font-size:14px;font-weight:700;margin-top:4px">Recent assets</div></div><a class="admin-btn" href="{{ route('admin.media.index') }}">Manage library</a></div><div style="display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:8px;padding:14px">@foreach($recentMedia as $a)<div style="aspect-ratio:1;border:1px solid #e4e7ec;border-radius:9px;overflow:hidden;background:#f6f7f9">@if(str_starts_with($a->mime_type??'','image/'))<img src="{{ route('store.media',['path'=>$a->path]) }}" alt="" style="width:100%;height:100%;object-fit:cover">@endif</div>@endforeach</div></section>
<style>@media(max-width:900px){.admin-page section:last-of-type>div:last-child{grid-template-columns:repeat(4,minmax(0,1fr))!important}}@media(max-width:550px){.admin-page section:last-of-type>div:last-child{grid-template-columns:repeat(2,minmax(0,1fr))!important}}</style>
@endsection
