<?php

return [
    'amerel-inspired-by-dior-jadore-elegant-womens-floral-perfume' => [
        'slug' => 'amerel-inspired-by-dior-jadore-elegant-womens-floral-perfume',
        'aliases' => ['Amerel'],
        'title' => 'Amerel | Elegant Women’s Floral Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Dior J’adore · Radiant, Graceful And Polished',
        'short_description' => 'Amerel is a radiant, graceful and polished women’s fragrance inspired by Dior J’adore, balancing citrus and fruity notes with jasmine, ylang-ylang and rose and a lasting musk and sandalwood dry-down.',
        'description' => 'Amerel is crafted for fragrance lovers who want a radiant, graceful and polished presence without losing refinement. Inspired by Dior J’adore, the composition opens with Citrus and Fruity Notes, creating the first impression with clarity and character. As it develops, Jasmine, Ylang-Ylang and Rose shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk and Sandalwood, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Ideal for daytime elegance, weddings, dinners and formal occasions. Apply to pulse points and allow the floral heart to develop naturally.',
        'story' => 'A study in contrast, Amerel moves from citrus and fruity notes into jasmine, ylang-ylang and rose before resting on musk and sandalwood. The result is radiant, graceful and polished, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Citrus', 'Fruity Notes'],
        'heart_notes' => ['Jasmine', 'Ylang-Ylang', 'Rose'],
        'base_notes' => ['Musk', 'Sandalwood'],
        'wear' => 'Ideal for daytime elegance, weddings, dinners and formal occasions. Apply to pulse points and allow the floral heart to develop naturally.',
        'notes' => 'Top: Citrus and Fruity Notes
Heart: Jasmine, Ylang-Ylang and Rose
Base: Musk and Sandalwood',
        'meta_title' => 'Amerel | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Amerel by Scents by Aamir in Pakistan. A radiant, graceful and polished fragrance with Citrus and Fruity Notes, Jasmine, Ylang-Ylang and Rose and Musk a…',
    ],
    'aventus-spirit-inspired-by-creed-aventus' => [
        'slug' => 'aventus-spirit-inspired-by-creed-aventus',
        'aliases' => ['Aventus Spirit'],
        'title' => 'Aventus Spirit - Inspired by Creed Aventus | Premium Luxury Perfume for Men',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Creed Aventus · Confident, Crisp And Commanding',
        'short_description' => 'Aventus Spirit is a confident, crisp and commanding men’s fragrance inspired by Creed Aventus, balancing bergamot, pineapple and black currant with birch, patchouli and jasmine and a lasting musk, oakmoss, ambergris and vanilla dry-down.',
        'description' => 'Aventus Spirit is crafted for fragrance lovers who want a confident, crisp and commanding presence without losing refinement. Inspired by Creed Aventus, the composition opens with Bergamot, Pineapple and Black Currant, creating the first impression with clarity and character. As it develops, Birch, Patchouli and Jasmine shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk, Oakmoss, Ambergris and Vanilla, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A versatile signature for office, events and evenings. Use 3–5 sprays on pulse points for a clean opening and a deeper woody dry-down.',
        'story' => 'A study in contrast, Aventus Spirit moves from bergamot, pineapple and black currant into birch, patchouli and jasmine before resting on musk, oakmoss, ambergris and vanilla. The result is confident, crisp and commanding, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Pineapple', 'Black Currant'],
        'heart_notes' => ['Birch', 'Patchouli', 'Jasmine'],
        'base_notes' => ['Musk', 'Oakmoss', 'Ambergris', 'Vanilla'],
        'wear' => 'A versatile signature for office, events and evenings. Use 3–5 sprays on pulse points for a clean opening and a deeper woody dry-down.',
        'notes' => 'Top: Bergamot, Pineapple and Black Currant
Heart: Birch, Patchouli and Jasmine
Base: Musk, Oakmoss, Ambergris and Vanilla',
        'meta_title' => 'Aventus Spirit Perfume | Scents by Aamir',
        'meta_description' => 'Shop Aventus Spirit by Scents by Aamir in Pakistan. A confident, crisp and commanding fragrance with Bergamot, Pineapple and Black Currant, Birch, Patchouli…',
    ],
    'blossom-shine' => [
        'slug' => 'blossom-shine',
        'aliases' => ['Blossom Shine'],
        'title' => 'Blossom Shine - Inspired by Victoria\'s Secret | Bright Women’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Victoria’s Secret floral styling · Bright, Feminine And Uplifting',
        'short_description' => 'Blossom Shine is a bright, feminine and uplifting women’s fragrance inspired by Victoria’s Secret floral styling, balancing passionfruit and grapefruit with peony and lily of the valley and a lasting musk and soft woods dry-down.',
        'description' => 'Blossom Shine is crafted for fragrance lovers who want a bright, feminine and uplifting presence without losing refinement. Inspired by Victoria’s Secret floral styling, the composition opens with passionfruit and grapefruit, creating the first impression with clarity and character. As it develops, peony and lily of the valley shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk and Soft Woods, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Best for daytime, casual outings and warm weather. Spray lightly on wrists, neck and clothing from a safe distance.',
        'story' => 'A study in contrast, Blossom Shine moves from passionfruit and grapefruit into peony and lily of the valley before resting on musk and soft woods. The result is bright, feminine and uplifting, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Passionfruit', 'Grapefruit'],
        'heart_notes' => ['Peony', 'Lily of the Valley'],
        'base_notes' => ['Musk', 'Soft Woods'],
        'wear' => 'Best for daytime, casual outings and warm weather. Spray lightly on wrists, neck and clothing from a safe distance.',
        'notes' => 'Top: passionfruit and grapefruit
Heart: peony and lily of the valley
Base: Musk and Soft Woods',
        'meta_title' => 'Blossom Shine Perfume | Scents by Aamir',
        'meta_description' => 'Shop Blossom Shine by Scents by Aamir in Pakistan. A bright, feminine and uplifting fragrance with passionfruit and grapefruit, peony and lily of the valley…',
    ],
    'bold-heat-inspired-by-office-for-men' => [
        'slug' => 'bold-heat-inspired-by-office-for-men',
        'aliases' => ['Bold Heat'],
        'title' => 'Bold Heat - Inspired by Office for Men | Modern Men’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Office for Men · Energetic, Assertive And Contemporary',
        'short_description' => 'Bold Heat is a energetic, assertive and contemporary men’s fragrance inspired by Office for Men, balancing citrus, bergamot and lemon with spicy accords, cardamom and lavender and a lasting amber, musk, vetiver and woody notes dry-down.',
        'description' => 'Bold Heat is crafted for fragrance lovers who want a energetic, assertive and contemporary presence without losing refinement. Inspired by Office for Men, the composition opens with Citrus, Bergamot and Lemon, creating the first impression with clarity and character. As it develops, Spicy Accords, Cardamom and Lavender shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Amber, Musk, Vetiver and Woody Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Built for workdays, meetings and evening plans. Apply to neck and wrists; avoid rubbing so the spicy heart and woody base evolve cleanly.',
        'story' => 'A study in contrast, Bold Heat moves from citrus, bergamot and lemon into spicy accords, cardamom and lavender before resting on amber, musk, vetiver and woody notes. The result is energetic, assertive and contemporary, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Citrus', 'Bergamot', 'Lemon'],
        'heart_notes' => ['Spicy Accords', 'Cardamom', 'Lavender'],
        'base_notes' => ['Amber', 'Musk', 'Vetiver', 'Woody Notes'],
        'wear' => 'Built for workdays, meetings and evening plans. Apply to neck and wrists; avoid rubbing so the spicy heart and woody base evolve cleanly.',
        'notes' => 'Top: Citrus, Bergamot and Lemon
Heart: Spicy Accords, Cardamom and Lavender
Base: Amber, Musk, Vetiver and Woody Notes',
        'meta_title' => 'Bold Heat Perfume | Scents by Aamir',
        'meta_description' => 'Shop Bold Heat by Scents by Aamir in Pakistan. A energetic, assertive and contemporary fragrance with Citrus, Bergamot and Lemon, Spicy Accords, Cardamom and…',
    ],
    'cherelle-inspired-by-dior-oud-ispahan-luxury-unisex-perfume' => [
        'slug' => 'cherelle-inspired-by-dior-oud-ispahan-luxury-unisex-perfume',
        'aliases' => ['Cherelle'],
        'title' => 'Cherelle Inspired by Dior Oud Ispahan | Luxury Oud Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Dior Oud Ispahan · Opulent, Dark And Refined',
        'short_description' => 'Cherelle Inspired by Dior Oud Ispahan is a opulent, dark and refined unisex fragrance inspired by Dior Oud Ispahan, balancing floral notes and soft spice accords with oud and rose and a lasting patchouli, labdanum and amber dry-down.',
        'description' => 'Cherelle Inspired by Dior Oud Ispahan is crafted for fragrance lovers who want a opulent, dark and refined presence without losing refinement. Inspired by Dior Oud Ispahan, the composition opens with floral notes and soft spice accords, creating the first impression with clarity and character. As it develops, oud and rose shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into patchouli, labdanum and amber, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Best suited to evenings, celebrations and cooler weather. Use a restrained application on pulse points because the oud-rose profile is naturally rich.',
        'story' => 'A study in contrast, Cherelle Inspired by Dior Oud Ispahan moves from floral notes and soft spice accords into oud and rose before resting on patchouli, labdanum and amber. The result is opulent, dark and refined, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Floral Notes', 'Soft Spice Accords'],
        'heart_notes' => ['Oud', 'Rose'],
        'base_notes' => ['Patchouli', 'Labdanum', 'Amber'],
        'wear' => 'Best suited to evenings, celebrations and cooler weather. Use a restrained application on pulse points because the oud-rose profile is naturally rich.',
        'notes' => 'Top: floral notes and soft spice accords
Heart: oud and rose
Base: patchouli, labdanum and amber',
        'meta_title' => 'Cherelle Inspired by Dior Oud Ispahan Perfume | Scents by Aamir',
        'meta_description' => 'Shop Cherelle Inspired by Dior Oud Ispahan by Scents by Aamir in Pakistan. A opulent, dark and refined fragrance with floral notes and soft spice accords, oud and rose a…',
    ],
    'dark-aure-inspired-by-nuit-de-feu-intense-smoky-arabic-unisex-perfume' => [
        'slug' => 'dark-aure-inspired-by-nuit-de-feu-intense-smoky-arabic-unisex-perfume',
        'aliases' => ['Dark Aure'],
        'title' => 'Dark Aure Inspired by Nuit de Feu | Intense Smoky Arabic Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Louis Vuitton Nuit de Feu · Smoky, Resinous And Mysterious',
        'short_description' => 'Dark Aure Inspired by Nuit de Feu is a smoky, resinous and mysterious unisex fragrance inspired by Louis Vuitton Nuit de Feu, balancing incense (somalian olibanum) with oud and leather and a lasting birch tar and woody notes dry-down.',
        'description' => 'Dark Aure Inspired by Nuit de Feu is crafted for fragrance lovers who want a smoky, resinous and mysterious presence without losing refinement. Inspired by Louis Vuitton Nuit de Feu, the composition opens with Incense (Somalian Olibanum), creating the first impression with clarity and character. As it develops, Oud and Leather shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Birch Tar and Woody Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Designed for winter nights, gatherings and statement wear. Two to four sprays are usually enough; let the incense and oud settle before judging the dry-down.',
        'story' => 'A study in contrast, Dark Aure Inspired by Nuit de Feu moves from incense (somalian olibanum) into oud and leather before resting on birch tar and woody notes. The result is smoky, resinous and mysterious, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Incense (Somalian Olibanum)'],
        'heart_notes' => ['Oud', 'Leather'],
        'base_notes' => ['Birch Tar', 'Woody Notes'],
        'wear' => 'Designed for winter nights, gatherings and statement wear. Two to four sprays are usually enough; let the incense and oud settle before judging the dry-down.',
        'notes' => 'Top: Incense (Somalian Olibanum)
Heart: Oud and Leather
Base: Birch Tar and Woody Notes',
        'meta_title' => 'Dark Aure Inspired by Nuit de Feu | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Dark Aure Inspired by Nuit de Feu by Scents by Aamir in Pakistan. A smoky, resinous and mysterious fragrance with Incense (Somalian Olibanum), Oud and L…',
    ],
    'dark-seduction' => [
        'slug' => 'dark-seduction',
        'aliases' => ['Dark Seduction'],
        'title' => 'Dark Seduction - Inspired by Yves Saint Laurent Black Opium | Women’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by YSL Black Opium · Addictive, Warm And Sensual',
        'short_description' => 'Dark Seduction is a addictive, warm and sensual women’s fragrance inspired by YSL Black Opium, balancing black coffee and pear with jasmine and orange blossom and a lasting vanilla, cedarwood and patchouli dry-down.',
        'description' => 'Dark Seduction is crafted for fragrance lovers who want a addictive, warm and sensual presence without losing refinement. Inspired by YSL Black Opium, the composition opens with black coffee and pear, creating the first impression with clarity and character. As it develops, jasmine and orange blossom shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into vanilla, cedarwood and patchouli, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A natural evening and date-night choice. Apply to pulse points and clothing for a richer gourmand trail, especially in cooler weather.',
        'story' => 'A study in contrast, Dark Seduction moves from black coffee and pear into jasmine and orange blossom before resting on vanilla, cedarwood and patchouli. The result is addictive, warm and sensual, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Black Coffee', 'Pear'],
        'heart_notes' => ['Jasmine', 'Orange Blossom'],
        'base_notes' => ['Vanilla', 'Cedarwood', 'Patchouli'],
        'wear' => 'A natural evening and date-night choice. Apply to pulse points and clothing for a richer gourmand trail, especially in cooler weather.',
        'notes' => 'Top: black coffee and pear
Heart: jasmine and orange blossom
Base: vanilla, cedarwood and patchouli',
        'meta_title' => 'Dark Seduction Perfume | Scents by Aamir',
        'meta_description' => 'Shop Dark Seduction by Scents by Aamir in Pakistan. A addictive, warm and sensual fragrance with black coffee and pear, jasmine and orange blossom and Vanilla, Am…',
    ],
    'delure-inspired-by-good-girl-sweet-seductive-womens-perfume' => [
        'slug' => 'delure-inspired-by-good-girl-sweet-seductive-womens-perfume',
        'aliases' => ['Delure'],
        'title' => 'Delure Inspired by Good Girl | Sweet & Seductive Women’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Carolina Herrera Good Girl · Creamy, Seductive And Elegant',
        'short_description' => 'Delure Inspired by Good Girl is a creamy, seductive and elegant women’s fragrance inspired by Carolina Herrera Good Girl, balancing almond, pear and citrus accords with jasmine, tuberose and orange blossom and a lasting tonka bean, cocoa, vanilla and sandalwood dry-down.',
        'description' => 'Delure Inspired by Good Girl is crafted for fragrance lovers who want a creamy, seductive and elegant presence without losing refinement. Inspired by Carolina Herrera Good Girl, the composition opens with Almond, Pear and Citrus Accords, creating the first impression with clarity and character. As it develops, Jasmine, Tuberose and Orange Blossom shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Tonka Bean, Cocoa, Vanilla and Sandalwood, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Ideal for dinners, parties and special evenings. Apply to neck, wrists and behind the ears for a smooth floral-gourmand progression.',
        'story' => 'A study in contrast, Delure Inspired by Good Girl moves from almond, pear and citrus accords into jasmine, tuberose and orange blossom before resting on tonka bean, cocoa, vanilla and sandalwood. The result is creamy, seductive and elegant, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Almond', 'Pear', 'Citrus Accords'],
        'heart_notes' => ['Jasmine', 'Tuberose', 'Orange Blossom'],
        'base_notes' => ['Tonka Bean', 'Cocoa', 'Vanilla', 'Sandalwood'],
        'wear' => 'Ideal for dinners, parties and special evenings. Apply to neck, wrists and behind the ears for a smooth floral-gourmand progression.',
        'notes' => 'Top: Almond, Pear and Citrus Accords
Heart: Jasmine, Tuberose and Orange Blossom
Base: Tonka Bean, Cocoa, Vanilla and Sandalwood',
        'meta_title' => 'Delure Inspired by Good Girl | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Delure Inspired by Good Girl by Scents by Aamir in Pakistan. A creamy, seductive and elegant fragrance with Almond, Pear and Citrus Accords, Jasmine, Tu…',
    ],
    'desert-soul-inspired-by-ombre-nomade-dark-oud-unisex-perfume' => [
        'slug' => 'desert-soul-inspired-by-ombre-nomade-dark-oud-unisex-perfume',
        'aliases' => ['Desert Soul'],
        'title' => 'Desert Soul Inspired by Ombre Nomade | Dark Oud Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Louis Vuitton Ombre Nomade · Dark, Smoky And Luxurious',
        'short_description' => 'Desert Soul Inspired by Ombre Nomade is a dark, smoky and luxurious unisex fragrance inspired by Louis Vuitton Ombre Nomade, balancing raspberry and spicy accords with oud, leather and rose and a lasting birch tar, woody resins and amber notes dry-down.',
        'description' => 'Desert Soul Inspired by Ombre Nomade is crafted for fragrance lovers who want a dark, smoky and luxurious presence without losing refinement. Inspired by Louis Vuitton Ombre Nomade, the composition opens with Raspberry and Spicy Accords, creating the first impression with clarity and character. As it develops, Oud, Leather and Rose shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Birch Tar, Woody Resins and Amber Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A bold choice for winter nights, weddings and Arabic-style gatherings. Use sparingly on pulse points and allow the dense oud and resin base to unfold.',
        'story' => 'A study in contrast, Desert Soul Inspired by Ombre Nomade moves from raspberry and spicy accords into oud, leather and rose before resting on birch tar, woody resins and amber notes. The result is dark, smoky and luxurious, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Raspberry', 'Spicy Accords'],
        'heart_notes' => ['Oud', 'Leather', 'Rose'],
        'base_notes' => ['Birch Tar', 'Woody Resins', 'Amber Notes'],
        'wear' => 'A bold choice for winter nights, weddings and Arabic-style gatherings. Use sparingly on pulse points and allow the dense oud and resin base to unfold.',
        'notes' => 'Top: Raspberry and Spicy Accords
Heart: Oud, Leather and Rose
Base: Birch Tar, Woody Resins and Amber Notes',
        'meta_title' => 'Desert Soul Inspired by Ombre Nomade Perfume | Scents by Aamir',
        'meta_description' => 'Shop Desert Soul Inspired by Ombre Nomade by Scents by Aamir in Pakistan. A dark, smoky and luxurious fragrance with Raspberry and Spicy Accords, Oud, Leathe…',
    ],
    'elyndor-inspired-by-roja-elysium-fresh-luxury-mens-perfume' => [
        'slug' => 'elyndor-inspired-by-roja-elysium-fresh-luxury-mens-perfume',
        'aliases' => ['Elyndor'],
        'title' => 'Elyndor Inspired by Roja Elysium | Fresh Luxury Men’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Roja Elysium · Fresh, Refined And Effortless',
        'short_description' => 'Elyndor Inspired by Roja Elysium is a fresh, refined and effortless men’s fragrance inspired by Roja Elysium, balancing grapefruit, bergamot and lemon with juniper berry, vetiver and floral accords and a lasting ambergris, musk and cedarwood dry-down.',
        'description' => 'Elyndor Inspired by Roja Elysium is crafted for fragrance lovers who want a fresh, refined and effortless presence without losing refinement. Inspired by Roja Elysium, the composition opens with Grapefruit, Bergamot and Lemon, creating the first impression with clarity and character. As it develops, Juniper Berry, Vetiver and Floral Accords shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Ambergris, Musk and Cedarwood, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Excellent for office, daytime and summer wear. Apply 4–6 sprays to pulse points for a bright citrus opening with a clean woody-musky finish.',
        'story' => 'A study in contrast, Elyndor Inspired by Roja Elysium moves from grapefruit, bergamot and lemon into juniper berry, vetiver and floral accords before resting on ambergris, musk and cedarwood. The result is fresh, refined and effortless, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Grapefruit', 'Bergamot', 'Lemon'],
        'heart_notes' => ['Juniper Berry', 'Vetiver', 'Floral Accords'],
        'base_notes' => ['Ambergris', 'Musk', 'Cedarwood'],
        'wear' => 'Excellent for office, daytime and summer wear. Apply 4–6 sprays to pulse points for a bright citrus opening with a clean woody-musky finish.',
        'notes' => 'Top: Grapefruit, Bergamot and Lemon
Heart: Juniper Berry, Vetiver and Floral Accords
Base: Ambergris, Musk and Cedarwood',
        'meta_title' => 'Elyndor Inspired by Roja Elysium | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Elyndor Inspired by Roja Elysium by Scents by Aamir in Pakistan. A fresh, refined and effortless fragrance with Grapefruit, Bergamot and Lemon, Juniper…',
    ],
    'floral-charm-scentsbyaamir' => [
        'slug' => 'floral-charm-scentsbyaamir',
        'aliases' => ['Floral Charm'],
        'title' => 'Floral Charm - Inspired by Gucci Flora | Elegant Women\'s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Gucci Flora · Soft, Romantic And Graceful',
        'short_description' => 'Floral Charm is a soft, romantic and graceful women’s fragrance inspired by Gucci Flora, balancing citrus and fruity notes with jasmine, peony and rose and a lasting musk and sandalwood dry-down.',
        'description' => 'Floral Charm is crafted for fragrance lovers who want a soft, romantic and graceful presence without losing refinement. Inspired by Gucci Flora, the composition opens with citrus and fruity notes, creating the first impression with clarity and character. As it develops, jasmine, peony and rose shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk and Sandalwood, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A polished everyday floral for brunches, work and celebrations. Apply lightly to wrists and neck to keep the floral character airy and elegant.',
        'story' => 'A study in contrast, Floral Charm moves from citrus and fruity notes into jasmine, peony and rose before resting on musk and sandalwood. The result is soft, romantic and graceful, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Citrus', 'Fruity Notes'],
        'heart_notes' => ['Jasmine', 'Peony', 'Rose'],
        'base_notes' => ['Musk', 'Sandalwood'],
        'wear' => 'A polished everyday floral for brunches, work and celebrations. Apply lightly to wrists and neck to keep the floral character airy and elegant.',
        'notes' => 'Top: citrus and fruity notes
Heart: jasmine, peony and rose
Base: Musk and Sandalwood',
        'meta_title' => 'Floral Charm Perfume | Scents by Aamir',
        'meta_description' => 'Shop Floral Charm by Scents by Aamir in Pakistan. A soft, romantic and graceful fragrance with citrus and fruity notes, jasmine, peony and rose and Musk…',
    ],
    'hivalta-inspired-by-nishane-hacivat-premium-unisex-perfume' => [
        'slug' => 'hivalta-inspired-by-nishane-hacivat-premium-unisex-perfume',
        'aliases' => ['Hivalta'],
        'title' => 'Hivalta Inspired by Nishane Hacivat | Premium Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Nishane Hacivat · Bright, Sophisticated And Enduring',
        'short_description' => 'Hivalta Inspired by Nishane Hacivat is a bright, sophisticated and enduring unisex fragrance inspired by Nishane Hacivat, balancing pineapple, bergamot and citrus accords with jasmine and woody notes and a lasting oakmoss, patchouli and amber dry-down.',
        'description' => 'Hivalta Inspired by Nishane Hacivat is crafted for fragrance lovers who want a bright, sophisticated and enduring presence without losing refinement. Inspired by Nishane Hacivat, the composition opens with pineapple, bergamot and citrus accords, creating the first impression with clarity and character. As it develops, jasmine and woody notes shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into oakmoss, patchouli and amber, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Works especially well for smart daytime wear, business settings and events. Spray on pulse points and let the citrus-fruit opening transition into mossy woods.',
        'story' => 'A study in contrast, Hivalta Inspired by Nishane Hacivat moves from pineapple, bergamot and citrus accords into jasmine and woody notes before resting on oakmoss, patchouli and amber. The result is bright, sophisticated and enduring, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Pineapple', 'Bergamot', 'Citrus Accords'],
        'heart_notes' => ['Jasmine', 'Woody Notes'],
        'base_notes' => ['Oakmoss', 'Patchouli', 'Amber'],
        'wear' => 'Works especially well for smart daytime wear, business settings and events. Spray on pulse points and let the citrus-fruit opening transition into mossy woods.',
        'notes' => 'Top: pineapple, bergamot and citrus accords
Heart: jasmine and woody notes
Base: oakmoss, patchouli and amber',
        'meta_title' => 'Hivalta Inspired by Nishane Hacivat Perfume | Scents by Aamir',
        'meta_description' => 'Shop Hivalta Inspired by Nishane Hacivat by Scents by Aamir in Pakistan. A bright, sophisticated and enduring fragrance with Pineapple, Grapefruit and Bergam…',
    ],
    'infinite-spark' => [
        'slug' => 'infinite-spark',
        'aliases' => ['Infinite Spark'],
        'title' => 'Infinite Spark | Luxury Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by a luminous modern fragrance profile · Luminous, Clean And Modern',
        'short_description' => 'Infinite Spark is a luminous, clean and modern unisex fragrance inspired by a luminous modern fragrance profile, balancing citrus and neroli with black tea and cardamom and a lasting ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil dry-down.',
        'description' => 'Infinite Spark is crafted for fragrance lovers who want a luminous, clean and modern presence without losing refinement. Inspired by a luminous modern fragrance profile, the composition opens with citrus and neroli, creating the first impression with clarity and character. As it develops, black tea and cardamom shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Designed for easy day-to-night wear. Apply to pulse points for a fresh opening that settles into a smooth amber-musky base.',
        'story' => 'A study in contrast, Infinite Spark moves from citrus and neroli into black tea and cardamom before resting on ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil. The result is luminous, clean and modern, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Citrus', 'Neroli'],
        'heart_notes' => ['Black Tea', 'Cardamom'],
        'base_notes' => ['Ambrox', 'Ambrosinide', 'Musk', 'Sandalwood', 'Natural Oud Wood', 'Siofi Oud Oil'],
        'wear' => 'Designed for easy day-to-night wear. Apply to pulse points for a fresh opening that settles into a smooth amber-musky base.',
        'notes' => 'Top: citrus and neroli
Heart: black tea and cardamom
Base: ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil',
        'meta_title' => 'Infinite Spark | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Infinite Spark by Scents by Aamir in Pakistan. A luminous, clean and modern fragrance with citrus and neroli, black tea and cardamom a…',
    ],
    'kavian-inspired-by-al-haitham-premium-arabic-unisex-perfume' => [
        'slug' => 'kavian-inspired-by-al-haitham-premium-arabic-unisex-perfume',
        'aliases' => ['Kavian'],
        'title' => 'Kavian Inspired by Al Haitham | Premium Arabic Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Al Haitham · Bold, Warm And Distinctly Arabic',
        'short_description' => 'Kavian Inspired by Al Haitham is a bold, warm and distinctly Arabic unisex fragrance inspired by Al Haitham, balancing saffron and bergamot with rose, violet and oud and a lasting ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil dry-down.',
        'description' => 'Kavian Inspired by Al Haitham is crafted for fragrance lovers who want a bold, warm and distinctly Arabic presence without losing refinement. Inspired by Al Haitham, the composition opens with saffron and bergamot, creating the first impression with clarity and character. As it develops, rose, violet and oud shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Best for evenings, formal gatherings and cooler seasons. A moderate application is enough to showcase the warm woody structure without overwhelming the room.',
        'story' => 'A study in contrast, Kavian Inspired by Al Haitham moves from saffron and bergamot into rose, violet and oud before resting on ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil. The result is bold, warm and distinctly Arabic, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Saffron', 'Bergamot'],
        'heart_notes' => ['Rose', 'Violet', 'Oud'],
        'base_notes' => ['Ambrox', 'Ambrosinide', 'Musk', 'Sandalwood', 'Natural Oud Wood', 'Siofi Oud Oil'],
        'wear' => 'Best for evenings, formal gatherings and cooler seasons. A moderate application is enough to showcase the warm woody structure without overwhelming the room.',
        'notes' => 'Top: saffron and bergamot
Heart: rose, violet and oud
Base: ambrox, ambrosinide, musk, sandalwood, natural oud wood and Siofi oud oil',
        'meta_title' => 'Kavian Inspired by Al Haitham | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Kavian Inspired by Al Haitham by Scents by Aamir in Pakistan. A bold, warm and distinctly Arabic fragrance with saffron and bergamot, Oud and Aromat…',
    ],
    'le-reve-dore-inspired-by-la-vie-est-belle-premium-womens-sweet-perfume' => [
        'slug' => 'le-reve-dore-inspired-by-la-vie-est-belle-premium-womens-sweet-perfume',
        'aliases' => ['Le Reve Dore', 'Le Rêve Doré'],
        'title' => 'Le Reve Dore Inspired by La Vie Est Belle | Premium Women’s Sweet Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Lancôme La Vie Est Belle · Golden, Sweet And Elegant',
        'short_description' => 'Le Reve Dore Inspired by La Vie Est Belle is a golden, sweet and elegant women’s fragrance inspired by Lancôme La Vie Est Belle, balancing pear and blackcurrant with iris, jasmine and orange blossom and a lasting praline, vanilla, tonka bean and patchouli dry-down.',
        'description' => 'Le Reve Dore Inspired by La Vie Est Belle is crafted for fragrance lovers who want a golden, sweet and elegant presence without losing refinement. Inspired by Lancôme La Vie Est Belle, the composition opens with Pear and Blackcurrant, creating the first impression with clarity and character. As it develops, Iris, Jasmine and Orange Blossom shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Praline, Vanilla, Tonka Bean and Patchouli, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Perfect for daily wear, weddings and evenings. Apply to pulse points for a radiant fruit-floral opening followed by a warm gourmand dry-down.',
        'story' => 'A study in contrast, Le Reve Dore Inspired by La Vie Est Belle moves from pear and blackcurrant into iris, jasmine and orange blossom before resting on praline, vanilla, tonka bean and patchouli. The result is golden, sweet and elegant, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Pear', 'Blackcurrant'],
        'heart_notes' => ['Iris', 'Jasmine', 'Orange Blossom'],
        'base_notes' => ['Praline', 'Vanilla', 'Tonka Bean', 'Patchouli'],
        'wear' => 'Perfect for daily wear, weddings and evenings. Apply to pulse points for a radiant fruit-floral opening followed by a warm gourmand dry-down.',
        'notes' => 'Top: Pear and Blackcurrant
Heart: Iris, Jasmine and Orange Blossom
Base: Praline, Vanilla, Tonka Bean and Patchouli',
        'meta_title' => 'Le Reve Dore Inspired by La Vie Est Belle Perfume | Scents by Aamir',
        'meta_description' => 'Shop Le Reve Dore Inspired by La Vie Est Belle by Scents by Aamir in Pakistan. A golden, sweet and elegant fragrance with Pear and Blackcurrant, Iris, Jasmin…',
    ],
    'night-rider-inspired-by-bleu-de-chanel' => [
        'slug' => 'night-rider-inspired-by-bleu-de-chanel',
        'aliases' => ['Night Rider'],
        'title' => 'Night Rider - Inspired by Bleu de Chanel | Sophisticated Men’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Bleu de Chanel · Clean, Mysterious And Composed',
        'short_description' => 'Night Rider is a clean, mysterious and composed men’s fragrance inspired by Bleu de Chanel, balancing citrus and grapefruit with aromatic notes, ginger and spices and a lasting incense, cedarwood and sandalwood dry-down.',
        'description' => 'Night Rider is crafted for fragrance lovers who want a clean, mysterious and composed presence without losing refinement. Inspired by Bleu de Chanel, the composition opens with Citrus and Grapefruit, creating the first impression with clarity and character. As it develops, Aromatic Notes, Ginger and Spices shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Incense, Cedarwood and Sandalwood, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A dependable signature for office, dinners and evening events. Spray on neck and wrists and allow the aromatic woods and incense to emerge gradually.',
        'story' => 'A study in contrast, Night Rider moves from citrus and grapefruit into aromatic notes, ginger and spices before resting on incense, cedarwood and sandalwood. The result is clean, mysterious and composed, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Citrus', 'Grapefruit'],
        'heart_notes' => ['Aromatic Notes', 'Ginger', 'Spices'],
        'base_notes' => ['Incense', 'Cedarwood', 'Sandalwood'],
        'wear' => 'A dependable signature for office, dinners and evening events. Spray on neck and wrists and allow the aromatic woods and incense to emerge gradually.',
        'notes' => 'Top: Citrus and Grapefruit
Heart: Aromatic Notes, Ginger and Spices
Base: Incense, Cedarwood and Sandalwood',
        'meta_title' => 'Night Rider Perfume | Scents by Aamir',
        'meta_description' => 'Shop Night Rider by Scents by Aamir in Pakistan. A clean, mysterious and composed fragrance with Citrus and Grapefruit, Aromatic Notes, Ginger and Spices and…',
    ],
    'ocean-spirit-inspired-by-acqua-di-gio' => [
        'slug' => 'ocean-spirit-inspired-by-acqua-di-gio',
        'aliases' => ['Ocean Spirit'],
        'title' => 'Ocean Spirit - Inspired by Acqua di Giò | Luxury Men\'s Perfume in Pakistan',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Acqua di Giò · Aquatic, Fresh And Masculine',
        'short_description' => 'Ocean Spirit is a aquatic, fresh and masculine men’s fragrance inspired by Acqua di Giò, balancing bergamot, lemon, lime and mandarin with jasmine, sea notes, calone and peach and a lasting musk, cedarwood, patchouli and amber dry-down.',
        'description' => 'Ocean Spirit is crafted for fragrance lovers who want a aquatic, fresh and masculine presence without losing refinement. Inspired by Acqua di Giò, the composition opens with Bergamot, Lemon, Lime and Mandarin, creating the first impression with clarity and character. As it develops, Jasmine, Sea Notes, Calone and Peach shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk, Cedarwood, Patchouli and Amber, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Ideal for daily use, work and warm weather, yet polished enough for formal settings. Apply 4–6 sprays to pulse points for a crisp aquatic trail.',
        'story' => 'A study in contrast, Ocean Spirit moves from bergamot, lemon, lime and mandarin into jasmine, sea notes, calone and peach before resting on musk, cedarwood, patchouli and amber. The result is aquatic, fresh and masculine, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Lemon', 'Lime', 'Mandarin'],
        'heart_notes' => ['Jasmine', 'Sea Notes', 'Calone', 'Peach'],
        'base_notes' => ['Musk', 'Cedarwood', 'Patchouli', 'Amber'],
        'wear' => 'Ideal for daily use, work and warm weather, yet polished enough for formal settings. Apply 4–6 sprays to pulse points for a crisp aquatic trail.',
        'notes' => 'Top: Bergamot, Lemon, Lime and Mandarin
Heart: Jasmine, Sea Notes, Calone and Peach
Base: Musk, Cedarwood, Patchouli and Amber',
        'meta_title' => 'Ocean Spirit Perfume | Scents by Aamir',
        'meta_description' => 'Shop Ocean Spirit by Scents by Aamir in Pakistan. A aquatic, fresh and masculine fragrance with Bergamot, Lemon, Lime and Mandarin, Jasmine, Sea Notes, Calon…',
    ],
    'opulent-rouge' => [
        'slug' => 'opulent-rouge',
        'aliases' => ['Opulent Rouge'],
        'title' => 'Opulent Rouge - Inspired by Baccarat Rouge 540 for Men and Women',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Baccarat Rouge 540 · Radiant, Luxurious And Memorable',
        'short_description' => 'Opulent Rouge is a radiant, luxurious and memorable unisex fragrance inspired by Baccarat Rouge 540, balancing jasmine, saffron and ambergris with fir resin and cedarwood and a lasting amber and woody notes dry-down.',
        'description' => 'Opulent Rouge is crafted for fragrance lovers who want a radiant, luxurious and memorable presence without losing refinement. Inspired by Baccarat Rouge 540, the composition opens with Jasmine, Saffron and Ambergris, creating the first impression with clarity and character. As it develops, Fir Resin and Cedarwood shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Amber and Woody Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Suited to special occasions, evenings and signature wear. Apply sparingly to pulse points and clothing; the amber-woody trail develops with warmth.',
        'story' => 'A study in contrast, Opulent Rouge moves from jasmine, saffron and ambergris into fir resin and cedarwood before resting on amber and woody notes. The result is radiant, luxurious and memorable, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Jasmine', 'Saffron', 'Ambergris'],
        'heart_notes' => ['Fir Resin', 'Cedarwood'],
        'base_notes' => ['Amber', 'Woody Notes'],
        'wear' => 'Suited to special occasions, evenings and signature wear. Apply sparingly to pulse points and clothing; the amber-woody trail develops with warmth.',
        'notes' => 'Top: Jasmine, Saffron and Ambergris
Heart: Fir Resin and Cedarwood
Base: Amber and Woody Notes',
        'meta_title' => 'Opulent Rouge Perfume | Scents by Aamir',
        'meta_description' => 'Shop Opulent Rouge by Scents by Aamir in Pakistan. A radiant, luxurious and memorable fragrance with Jasmine, Saffron and Ambergris, Fir Resin and Cedarwood…',
    ],
    'royal-noxis-inspired-by-clive-christian-1872-luxury-mens-perfume' => [
        'slug' => 'royal-noxis-inspired-by-clive-christian-1872-luxury-mens-perfume',
        'aliases' => ['Royal Noxis'],
        'title' => 'Royal Noxis Inspired by Clive Christian 1872 | Luxury Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Clive Christian 1872 · Aristocratic, Green And Refined',
        'short_description' => 'Royal Noxis Inspired by Clive Christian 1872 is a aristocratic, green and refined men’s fragrance inspired by Clive Christian 1872, balancing bergamot, pineapple and citrus accords with herbal notes and floral accords and a lasting cedarwood, patchouli and woody notes dry-down.',
        'description' => 'Royal Noxis Inspired by Clive Christian 1872 is crafted for fragrance lovers who want a aristocratic, green and refined presence without losing refinement. Inspired by Clive Christian 1872, the composition opens with bergamot, pineapple and citrus accords, creating the first impression with clarity and character. As it develops, herbal notes and floral accords shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into cedarwood, patchouli and woody notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A refined choice for formal daytime wear and sophisticated evenings. Apply to pulse points for a crisp green opening and a composed woody finish.',
        'story' => 'A study in contrast, Royal Noxis Inspired by Clive Christian 1872 moves from bergamot, pineapple and citrus accords into herbal notes and floral accords before resting on cedarwood, patchouli and woody notes. The result is aristocratic, green and refined, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Pineapple', 'Citrus Accords'],
        'heart_notes' => ['Herbal Notes', 'Floral Accords'],
        'base_notes' => ['Cedarwood', 'Patchouli', 'Woody Notes'],
        'wear' => 'A refined choice for formal daytime wear and sophisticated evenings. Apply to pulse points for a crisp green opening and a composed woody finish.',
        'notes' => 'Top: bergamot, pineapple and citrus accords
Heart: herbal notes and floral accords
Base: cedarwood, patchouli and woody notes',
        'meta_title' => 'Royal Noxis Inspired by Clive Christian 1872 Perfume | Scents by Aamir',
        'meta_description' => 'Shop Royal Noxis Inspired by Clive Christian 1872 by Scents by Aamir in Pakistan. A aristocratic, green and refined fragrance with Citrus, Bergamot and Green…',
    ],
    'silver-breeze-inspired-by-creed-silver-mountain-water-fresh-unisex-perfume' => [
        'slug' => 'silver-breeze-inspired-by-creed-silver-mountain-water-fresh-unisex-perfume',
        'aliases' => ['Silver Breeze'],
        'title' => 'Silver Breeze - Inspired by Creed Silver Mountain Water | Fresh Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Creed Silver Mountain Water · Cool, Airy And Polished',
        'short_description' => 'Silver Breeze is a cool, airy and polished unisex fragrance inspired by Creed Silver Mountain Water, balancing bergamot, mandarin and fresh citrus with blackcurrant, green tea and fresh accords and a lasting musk and woody notes dry-down.',
        'description' => 'Silver Breeze is crafted for fragrance lovers who want a cool, airy and polished presence without losing refinement. Inspired by Creed Silver Mountain Water, the composition opens with Bergamot, Mandarin and Fresh Citrus, creating the first impression with clarity and character. As it develops, Blackcurrant, Green Tea and Fresh Accords shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Musk and Woody Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Especially suited to daytime, office and hot weather. Apply generously but cleanly to pulse points for a transparent fresh trail.',
        'story' => 'A study in contrast, Silver Breeze moves from bergamot, mandarin and fresh citrus into blackcurrant, green tea and fresh accords before resting on musk and woody notes. The result is cool, airy and polished, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Mandarin', 'Fresh Citrus'],
        'heart_notes' => ['Blackcurrant', 'Green Tea', 'Fresh Accords'],
        'base_notes' => ['Musk', 'Woody Notes'],
        'wear' => 'Especially suited to daytime, office and hot weather. Apply generously but cleanly to pulse points for a transparent fresh trail.',
        'notes' => 'Top: Bergamot, Mandarin and Fresh Citrus
Heart: Blackcurrant, Green Tea and Fresh Accords
Base: Musk and Woody Notes',
        'meta_title' => 'Silver Breeze Perfume | Scents by Aamir',
        'meta_description' => 'Shop Silver Breeze by Scents by Aamir in Pakistan. A cool, airy and polished fragrance with Bergamot, Mandarin and Fresh Citrus, Blackcurrant, Green Tea and…',
    ],
    'smoky-chic' => [
        'slug' => 'smoky-chic',
        'aliases' => ['Smoky Chic'],
        'title' => 'Smoky Chic - Inspired by Gris Dior | Sophisticated Unisex Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Gris Dior · Smoky, Elegant And Contemporary',
        'short_description' => 'Smoky Chic is a smoky, elegant and contemporary unisex fragrance inspired by Gris Dior, balancing bergamot and pink pepper with iris, rose and amber and a lasting vetiver, cedarwood and musk dry-down.',
        'description' => 'Smoky Chic is crafted for fragrance lovers who want a smoky, elegant and contemporary presence without losing refinement. Inspired by Gris Dior, the composition opens with Bergamot and Pink Pepper, creating the first impression with clarity and character. As it develops, Iris, Rose and Amber shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Vetiver, Cedarwood and Musk, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Ideal for elegant day-to-evening wear and signature use. Apply to pulse points and let the iris, rose and woods gain depth on skin.',
        'story' => 'A study in contrast, Smoky Chic moves from bergamot and pink pepper into iris, rose and amber before resting on vetiver, cedarwood and musk. The result is smoky, elegant and contemporary, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Pink Pepper'],
        'heart_notes' => ['Iris', 'Rose', 'Amber'],
        'base_notes' => ['Vetiver', 'Cedarwood', 'Musk'],
        'wear' => 'Ideal for elegant day-to-evening wear and signature use. Apply to pulse points and let the iris, rose and woods gain depth on skin.',
        'notes' => 'Top: Bergamot and Pink Pepper
Heart: Iris, Rose and Amber
Base: Vetiver, Cedarwood and Musk',
        'meta_title' => 'Smoky Chic Perfume | Scents by Aamir',
        'meta_description' => 'Shop Smoky Chic by Scents by Aamir in Pakistan. A smoky, elegant and contemporary fragrance with Bergamot and Pink Pepper, Iris, Rose and Amber and Vetiver…',
    ],
    'vauren-inspired-by-ysl-tuxedo-spicy-amber-luxury-mens-perfume' => [
        'slug' => 'vauren-inspired-by-ysl-tuxedo-spicy-amber-luxury-mens-perfume',
        'aliases' => ['Vauren'],
        'title' => 'Vauren Inspired by YSL Tuxedo | Spicy Amber Luxury Men’s Perfume',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by YSL Tuxedo · Spicy, Tailored And Seductive',
        'short_description' => 'Vauren Inspired by YSL Tuxedo is a spicy, tailored and seductive men’s fragrance inspired by YSL Tuxedo, balancing bergamot and black pepper with patchouli, spices and floral accords and a lasting ambergris, vanilla and woody notes dry-down.',
        'description' => 'Vauren Inspired by YSL Tuxedo is crafted for fragrance lovers who want a spicy, tailored and seductive presence without losing refinement. Inspired by YSL Tuxedo, the composition opens with Bergamot and Black Pepper, creating the first impression with clarity and character. As it develops, Patchouli, Spices and Floral Accords shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Ambergris, Vanilla and Woody Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. Best for evenings, dinners, formal events and cool weather. Use 3–5 sprays on pulse points to showcase the peppery opening and smooth amber-vanilla finish.',
        'story' => 'A study in contrast, Vauren Inspired by YSL Tuxedo moves from bergamot and black pepper into patchouli, spices and floral accords before resting on ambergris, vanilla and woody notes. The result is spicy, tailored and seductive, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Black Pepper'],
        'heart_notes' => ['Patchouli', 'Spices', 'Floral Accords'],
        'base_notes' => ['Ambergris', 'Vanilla', 'Woody Notes'],
        'wear' => 'Best for evenings, dinners, formal events and cool weather. Use 3–5 sprays on pulse points to showcase the peppery opening and smooth amber-vanilla finish.',
        'notes' => 'Top: Bergamot and Black Pepper
Heart: Patchouli, Spices and Floral Accords
Base: Ambergris, Vanilla and Woody Notes',
        'meta_title' => 'Vauren Inspired by YSL Tuxedo | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Vauren Inspired by YSL Tuxedo by Scents by Aamir in Pakistan. A spicy, tailored and seductive fragrance with Bergamot and Black Pepper, Patchouli, Spice…',
    ],
    'wild-intense' => [
        'slug' => 'wild-intense',
        'aliases' => ['Wild Intense'],
        'title' => 'Wild Intense | Most Popular Perfume for Men',
        'type' => 'fragrance',
        'subtitle' => 'Inspired by Dior Sauvage · Fresh, Rugged And Magnetic',
        'short_description' => 'Wild Intense is a fresh, rugged and magnetic men’s fragrance inspired by Dior Sauvage, balancing bergamot and pepper with lavender, geranium and aromatic accords and a lasting ambroxan, cedarwood and amber notes dry-down.',
        'description' => 'Wild Intense is crafted for fragrance lovers who want a fresh, rugged and magnetic presence without losing refinement. Inspired by Dior Sauvage, the composition opens with Bergamot and Pepper, creating the first impression with clarity and character. As it develops, Lavender, Geranium and Aromatic Accords shape the heart, adding texture, depth and a more distinctive signature on skin. The dry-down settles into Ambroxan, Cedarwood and Amber Notes, giving the fragrance its lasting warmth, structure and polished finish. Rather than feeling flat or one-dimensional, the scent moves in stages from opening freshness to its fuller centre and finally to a smoother base. It is designed as an easy luxury choice within the Scents by Aamir collection for customers who appreciate recognizable fragrance direction, strong presence and a well-balanced wearing experience in Pakistan. A versatile day-to-night men’s scent for work, casual wear and events. Apply 4–6 sprays to pulse points for fresh projection and a dry woody-amber trail.',
        'story' => 'A study in contrast, Wild Intense moves from bergamot and pepper into lavender, geranium and aromatic accords before resting on ambroxan, cedarwood and amber notes. The result is fresh, rugged and magnetic, with each stage designed to reveal itself gradually rather than all at once.',
        'top_notes' => ['Bergamot', 'Pepper'],
        'heart_notes' => ['Lavender', 'Geranium', 'Aromatic Accords'],
        'base_notes' => ['Ambroxan', 'Cedarwood', 'Amber Notes'],
        'wear' => 'A versatile day-to-night men’s scent for work, casual wear and events. Apply 4–6 sprays to pulse points for fresh projection and a dry woody-amber trail.',
        'notes' => 'Top: Bergamot and Pepper
Heart: Lavender, Geranium and Aromatic Accords
Base: Ambroxan, Cedarwood and Amber Notes',
        'meta_title' => 'Wild Intense | Scents by Aamir Pakistan',
        'meta_description' => 'Shop Wild Intense by Scents by Aamir in Pakistan. A fresh, rugged and magnetic fragrance with Bergamot and Pepper, Lavender, Geranium and Aromatic Accords an…',
    ],
    'custom-perfume-tester-box' => [
        'slug' => 'custom-perfume-tester-box',
        'aliases' => ['Custom Perfume Tester Box'],
        'title' => 'Custom Perfume Tester Box - Select Any 5 Scents (5ml Each)',
        'type' => 'tester',
        'subtitle' => '5 × 5ml Discovery Experience',
        'short_description' => 'Choose any five 5ml scents from the Scents by Aamir collection and build a personalised discovery set before committing to a full bottle.',
        'description' => 'Custom Perfume Tester Box - Select Any 5 Scents (5ml Each) is designed for customers who want to experience the Scents by Aamir collection before choosing full-size bottles. Each box contains five convenient 5ml sprays, making it easier to compare fragrances across different days, settings and moods instead of judging a scent from a single spray. The discovery format is compact enough for travel and practical enough for gifting, while still giving each selected fragrance enough wear time to understand its opening, development and dry-down. Choose any five 5ml scents from the Scents by Aamir collection and build a personalised discovery set before committing to a full bottle. The box is about exploration rather than representing one single fragrance, so it intentionally does not use a fabricated top, heart or base note pyramid. Store the sprays in a cool, dry place away from direct heat and sunlight, and test each fragrance on clean skin for the most useful comparison.',
        'story' => 'A signature scent is easier to choose when it has been lived with. This tester box turns fragrance discovery into a considered ritual: wear, compare, revisit and then decide which composition deserves a place in your full-bottle collection.',
        'top_notes' => [],
        'heart_notes' => [],
        'base_notes' => [],
        'wear' => 'Test one fragrance at a time on clean skin. Allow the scent to develop for several hours before comparing it with another option.',
        'notes' => '',
        'meta_title' => 'Custom Perfume Tester Box | Scents by Aamir Pakistan',
        'meta_description' => 'Choose any five 5ml scents from the Scents by Aamir collection and build a personalised discovery set before committing to a full bottle. Shop the Scents by A',
    ],
    'female-perfume-tester-box' => [
        'slug' => 'female-perfume-tester-box',
        'aliases' => ['Female Perfume Tester Box'],
        'title' => 'Female Perfume Tester Box | 5 x 5ml Luxury Perfume Discovery Set',
        'type' => 'tester',
        'subtitle' => '5 × 5ml Discovery Experience',
        'short_description' => 'Explore five 5ml women’s fragrances in a convenient discovery format designed for comparison, gifting, travel and finding a signature scent.',
        'description' => 'Female Perfume Tester Box | 5 x 5ml Luxury Perfume Discovery Set is designed for customers who want to experience the Scents by Aamir collection before choosing full-size bottles. Each box contains five convenient 5ml sprays, making it easier to compare fragrances across different days, settings and moods instead of judging a scent from a single spray. The discovery format is compact enough for travel and practical enough for gifting, while still giving each selected fragrance enough wear time to understand its opening, development and dry-down. Explore five 5ml women’s fragrances in a convenient discovery format designed for comparison, gifting, travel and finding a signature scent. The box is about exploration rather than representing one single fragrance, so it intentionally does not use a fabricated top, heart or base note pyramid. Store the sprays in a cool, dry place away from direct heat and sunlight, and test each fragrance on clean skin for the most useful comparison.',
        'story' => 'A signature scent is easier to choose when it has been lived with. This tester box turns fragrance discovery into a considered ritual: wear, compare, revisit and then decide which composition deserves a place in your full-bottle collection.',
        'top_notes' => [],
        'heart_notes' => [],
        'base_notes' => [],
        'wear' => 'Test one fragrance at a time on clean skin. Allow the scent to develop for several hours before comparing it with another option.',
        'notes' => '',
        'meta_title' => 'Female Perfume Tester Box | Scents by Aamir Pakistan',
        'meta_description' => 'Explore five 5ml women’s fragrances in a convenient discovery format designed for comparison, gifting, travel and finding a signature scent. Shop the Scents b',
    ],
    'mens-perfume-tester-box' => [
        'slug' => 'mens-perfume-tester-box',
        'aliases' => ['Men’s Perfume Tester Box', 'Men\'s Perfume Tester Box'],
        'title' => 'Men’s Perfume Tester Box | 5 x 5ml Luxury Perfume Discovery Set',
        'type' => 'tester',
        'subtitle' => '5 × 5ml Discovery Experience',
        'short_description' => 'Explore five 5ml men’s fragrances side by side before choosing a full bottle, with a compact format suited to gifting, travel and everyday testing.',
        'description' => 'Men’s Perfume Tester Box | 5 x 5ml Luxury Perfume Discovery Set is designed for customers who want to experience the Scents by Aamir collection before choosing full-size bottles. Each box contains five convenient 5ml sprays, making it easier to compare fragrances across different days, settings and moods instead of judging a scent from a single spray. The discovery format is compact enough for travel and practical enough for gifting, while still giving each selected fragrance enough wear time to understand its opening, development and dry-down. Explore five 5ml men’s fragrances side by side before choosing a full bottle, with a compact format suited to gifting, travel and everyday testing. The box is about exploration rather than representing one single fragrance, so it intentionally does not use a fabricated top, heart or base note pyramid. Store the sprays in a cool, dry place away from direct heat and sunlight, and test each fragrance on clean skin for the most useful comparison.',
        'story' => 'A signature scent is easier to choose when it has been lived with. This tester box turns fragrance discovery into a considered ritual: wear, compare, revisit and then decide which composition deserves a place in your full-bottle collection.',
        'top_notes' => [],
        'heart_notes' => [],
        'base_notes' => [],
        'wear' => 'Test one fragrance at a time on clean skin. Allow the scent to develop for several hours before comparing it with another option.',
        'notes' => '',
        'meta_title' => 'Men’s Perfume Tester Box | Scents by Aamir Pakistan',
        'meta_description' => 'Explore five 5ml men’s fragrances side by side before choosing a full bottle, with a compact format suited to gifting, travel and everyday testing. Shop the S',
    ],
];
