@extends('layouts.store')
@section('title','Fragrance Finder — Scents by Aamir')
@section('content')
<div x-data="{step:{{ $recommendations->isNotEmpty()?4:1 }},mood:@js($answers['mood']??''),intensity:@js($answers['intensity']??''),occasion:@js($answers['occasion']??''),choose(k,v){this[k]=v;if(this.step<3)this.step++;else this.submit()},submit(){const p=new URLSearchParams({mood:this.mood,intensity:this.intensity,occasion:this.occasion});location.href='{{ route('finder') }}?'+p.toString()},reset(){location.href='{{ route('finder') }}'}}" class="min-h-screen bg-black pt-[100px] text-white">
<section class="house-container py-12 lg:py-16"><div class="grid gap-8 border-b border-white/15 pb-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p class="ui-label text-white/40">Guided Discovery</p><h1 class="mt-4 display-serif text-6xl leading-[.88] sm:text-8xl">Find your fragrance.</h1></div><p class="ui-label text-white/40" x-show="step<4">Step <span x-text="step"></span> / 03</p></div></section>
<section class="house-container pb-20">
<div x-show="step===1"><p class="ui-label text-white/40">01 — Mood</p><h2 class="mt-4 display-serif text-5xl">How should it feel?</h2><div class="mt-10 grid gap-px bg-white/15 sm:grid-cols-2 lg:grid-cols-3">@foreach(['Quiet','Magnetic','Fresh','Warm','Dark','Celebratory'] as $x)<button @click="choose('mood',@js($x))" class="min-h-[180px] bg-black p-7 text-left transition hover:bg-white hover:text-black"><span class="display-serif text-4xl">{{ $x }}</span></button>@endforeach</div></div>
<div x-cloak x-show="step===2"><p class="ui-label text-white/40">02 — Intensity</p><h2 class="mt-4 display-serif text-5xl">How present should it be?</h2><div class="mt-10 grid gap-px bg-white/15 sm:grid-cols-3">@foreach(['Soft','Moderate','Strong'] as $x)<button @click="choose('intensity',@js($x))" class="min-h-[210px] bg-black p-7 text-left transition hover:bg-white hover:text-black"><span class="display-serif text-4xl">{{ $x }}</span></button>@endforeach</div></div>
<div x-cloak x-show="step===3"><p class="ui-label text-white/40">03 — Occasion</p><h2 class="mt-4 display-serif text-5xl">Where will you wear it?</h2><div class="mt-10 grid gap-px bg-white/15 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Everyday','Evening','Formal','Gifting'] as $x)<button @click="choose('occasion',@js($x))" class="min-h-[210px] bg-black p-7 text-left transition hover:bg-white hover:text-black"><span class="display-serif text-4xl">{{ $x }}</span></button>@endforeach</div></div>
<div x-cloak x-show="step===4"><div class="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p class="ui-label text-white/40">Your Direction</p><h2 class="mt-4 display-serif text-6xl">A considered edit.</h2><div class="mt-8 space-y-3 text-sm text-white/60"><p>Mood: <span class="text-white" x-text="mood"></span></p><p>Intensity: <span class="text-white" x-text="intensity"></span></p><p>Occasion: <span class="text-white" x-text="occasion"></span></p></div><button @click="reset" class="btn-outline mt-8 border-white text-white">Start again</button></div><div class="grid gap-4 sm:grid-cols-2">@forelse($recommendations as $p)<a href="{{ route('product.show',$p['slug']) }}" class="group bg-white text-black"><div class="relative aspect-[4/5] overflow-hidden">@if($p['image'])<img src="{{ $p['image'] }}" class="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]">@endif</div><div class="p-5"><p class="ui-label text-black/38">{{ $p['family'] }}</p><h3 class="mt-2 display-serif text-4xl">{{ $p['name'] }}</h3><p class="mt-3 text-sm">PKR {{ $p['price'] }}</p></div></a>@empty<p class="text-white/50">Complete the three steps to see your edit.</p>@endforelse</div></div></div>
</section></div>@endsection
