@extends('layouts.store')
@php $isDark=($page['theme']??'light')==='dark'; @endphp
@section('title',($page['meta_title']??$page['title']).' — Scents by Aamir')
@section('description',$page['meta_description']??$page['intro']??'')
@section('content')
<section class="{{ $isDark?'bg-[#11100f] text-white':'bg-[#f7f6f2] text-black' }} pt-[100px]"><div class="house-container py-14 lg:py-20"><p class="ui-label {{ $isDark?'text-white/35':'text-black/35' }}">{{ $page['eyebrow']??'House Information' }}</p><div class="mt-5 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><h1 class="display-serif max-w-5xl text-[50px] leading-[.92] sm:text-[66px] lg:text-[76px]">{{ $page['title'] }}</h1><p class="max-w-xl text-sm leading-7 {{ $isDark?'text-white/55':'text-black/52' }}">{{ $page['intro'] }}</p></div></div></section>
<section class="{{ $isDark?'bg-black text-white':'bg-white text-black' }}"><div class="house-container py-12 lg:py-18">@if(($page['source']??'config')==='db')<article class="mx-auto max-w-4xl text-base leading-8">{!! $page['content'] !!}</article>@else<div class="divide-y {{ $isDark?'divide-white/15 border-white/15':'divide-black/10 border-black/10' }} border-y">@foreach($page['sections'] as $index=>$section)<details class="group py-7" {{ $index===0?'open':'' }}><summary class="grid cursor-pointer list-none gap-4 lg:grid-cols-[80px_1fr_auto] lg:items-center"><span class="ui-label opacity-30">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</span><h2 class="display-serif text-[34px] sm:text-[40px]">{{ $section['title'] }}</h2><span class="text-xl transition group-open:rotate-45">+</span></summary><p class="mt-5 max-w-2xl text-sm leading-7 opacity-55 lg:ml-[80px]">{{ $section['copy'] }}</p></details>@endforeach</div>@endif</div></section>
<section class="{{ $isDark?'bg-[#f7f6f2] text-black':'bg-[#11100f] text-white' }}"><div class="house-container grid gap-8 py-12 sm:grid-cols-[1fr_auto] sm:items-center"><div><p class="ui-label opacity-35">Customer Care</p><h2 class="mt-3 display-serif text-[38px] sm:text-[46px]">Need personal assistance?</h2></div><a href="{{ route('contact') }}" class="{{ $isDark?'btn-solid':'btn-outline border-white text-white' }}">Contact support</a></div></section>
@endsection
