@extends('layouts.store')
@section('title','Journal — Scents by Aamir')
@section('description','Materials, memory and the culture surrounding fragrance.')
@section('content')
<section class="bg-[#f7f6f2] pt-[100px] text-black"><div class="house-container py-14 lg:py-20"><p class="ui-label text-black/35">Editorial</p><div class="mt-4 grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><h1 class="display-serif text-6xl leading-[.88] sm:text-8xl lg:text-[8.5rem]">Journal</h1><p class="max-w-lg text-sm leading-7 text-black/52">Materials, memory and the culture surrounding fragrance.</p></div></div></section>
<section class="bg-white"><div class="house-container py-12 lg:py-16">
@php($featured=$posts->first())
@if($featured)
<a href="{{ route('journal.show',$featured->slug) }}" class="group grid overflow-hidden bg-black text-white lg:grid-cols-[1.15fr_.85fr]"><div class="relative min-h-[620px] overflow-hidden">@if($featured->featured_image_path)<img src="{{ str_starts_with($featured->featured_image_path,'http')||str_starts_with($featured->featured_image_path,'/')?$featured->featured_image_path:asset('storage/'.$featured->featured_image_path) }}" alt="{{ $featured->title }}" class="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.02]">@endif<div class="absolute inset-0 bg-black/15"></div></div><div class="flex min-h-[520px] items-end p-8 sm:p-12 lg:p-14"><div><p class="ui-label text-white/45">{{ $featured->eyebrow ?: 'House Journal' }} · {{ $featured->published_at?->format('d M Y') ?: 'Editorial' }}</p><h2 class="mt-4 display-serif text-6xl leading-[.9] sm:text-7xl">{{ $featured->title }}</h2><p class="mt-6 max-w-lg text-sm leading-7 text-white/58">{{ $featured->excerpt }}</p><span class="mt-8 inline-block ui-label">Read story →</span></div></div></a>
<div class="mt-4 grid gap-4 md:grid-cols-2">@foreach($posts->skip(1) as $article)<a href="{{ route('journal.show',$article->slug) }}" class="group border border-black/10 bg-[#f7f6f2]"><div class="relative aspect-[16/11] overflow-hidden bg-black/5">@if($article->featured_image_path)<img src="{{ str_starts_with($article->featured_image_path,'http')||str_starts_with($article->featured_image_path,'/')?$article->featured_image_path:asset('storage/'.$article->featured_image_path) }}" alt="{{ $article->title }}" loading="lazy" class="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]">@endif</div><div class="p-6 sm:p-8"><p class="ui-label text-black/35">{{ $article->eyebrow ?: 'Journal' }}</p><h3 class="mt-3 display-serif text-5xl leading-[.95]">{{ $article->title }}</h3><p class="mt-4 text-sm leading-6 text-black/50">{{ $article->excerpt }}</p><span class="mt-6 inline-block ui-label">Read →</span></div></a>@endforeach</div>
@else<div class="py-20 text-center"><h2 class="display-serif text-5xl">The journal is being composed.</h2></div>@endif
</div></section>@endsection
