@extends('layouts.store')
@section('title','Wishlist — Scents by Aamir')
@section('content')
<section x-data x-init="$store.commerce.syncWishlist()" class="min-h-screen bg-[#f7f6f2] pt-[100px] text-black">
<div class="border-b border-black/10 bg-white"><div class="house-container py-10 sm:py-14"><div class="flex items-end justify-between gap-6"><div><p class="ui-label text-black/35">Saved Selection</p><h1 class="mt-3 display-serif text-[50px] sm:text-[64px]">Your wishlist.</h1></div><p class="ui-label text-black/35"><span x-text="$store.commerce.wishlist.length"></span> saved</p></div></div></div>
<div class="house-container py-12 lg:py-16">
<template x-if="$store.commerce.wishlist.length===0"><div class="grid min-h-[400px] place-items-center border border-black/10 bg-white text-center"><div><h2 class="display-serif text-[44px]">Nothing saved yet.</h2><p class="mt-4 text-sm text-black/48">Keep the fragrances you want to return to.</p><a href="{{ route('shop') }}" class="btn-solid mt-7">Explore fragrances</a></div></div></template>
<div class="grid gap-x-4 gap-y-12 sm:grid-cols-2 lg:grid-cols-4"><template x-for="item in $store.commerce.wishlist" :key="item.product_id||item.slug"><article class="group"><div class="relative aspect-[4/5] overflow-hidden bg-[#e9e5dd]"><a :href="'/product/'+item.slug" class="absolute inset-0"><img :src="item.image" :alt="item.name" class="h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]"></a><button @click="$store.commerce.toggleWishlist(item)" class="absolute right-3 top-3 z-10 grid h-9 w-9 place-items-center rounded-full bg-white/90">♥</button></div><div class="pt-4"><div class="flex justify-between gap-4"><div><a :href="'/product/'+item.slug" class="text-[12px] font-medium uppercase" x-text="item.name"></a><p class="mt-1 text-[9px] uppercase tracking-[.14em] text-black/42" x-text="item.family"></p></div><p class="text-[11px]">PKR <span x-text="Number(item.price_value||0).toLocaleString()"></span></p></div><a :href="'/product/'+item.slug" class="btn-outline mt-4 w-full">View fragrance</a></div></article></template></div>
<section class="mt-20 border-t border-black/10 pt-12"><div class="flex items-end justify-between gap-5"><div><p class="ui-label text-black/30">Recently Viewed</p><h2 class="mt-3 display-serif text-[42px]">Return to your trail.</h2></div><button x-show="$store.commerce.recentlyViewed.length" @click="$store.commerce.clearRecentlyViewed()" class="text-link">Clear history</button></div>
<template x-if="$store.commerce.recentlyViewed.length===0"><p class="mt-7 text-sm text-black/45">Fragrances you view will appear here on this device.</p></template>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><template x-for="item in $store.commerce.recentlyViewed.slice(0,4)" :key="'recent-'+(item.product_id||item.slug)"><a :href="'/product/'+item.slug" class="group grid grid-cols-[90px_1fr] gap-4 bg-white p-3"><div class="aspect-[4/5] overflow-hidden bg-[#eceae4]"><img :src="item.image" :alt="item.name" class="h-full w-full object-cover"></div><div class="self-center"><p class="ui-label text-black/30" x-text="item.family||'Fragrance'"></p><h3 class="mt-2 display-serif text-[25px] leading-none" x-text="item.name"></h3><p class="mt-3 text-xs">PKR <span x-text="Number(item.price_value||0).toLocaleString()"></span></p></div></a></template></div></section>
</div></section>
@endsection
