@extends('admin.layouts.app')
@section('title','Orders') @section('header','Orders')
@section('content')
@if(session('success'))<div class="mb-6 border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm">{{ session('success') }}</div>@endif
<form class="mb-6 grid gap-3 md:grid-cols-[1fr_180px_180px_auto]">
<input name="q" value="{{ request('q') }}" placeholder="Order, customer, email" class="border border-black/15 bg-white px-4 py-3 text-sm">
<select name="status" class="border border-black/15 bg-white px-3 py-3 text-sm"><option value="">All statuses</option>@foreach(['pending','confirmed','processing','shipped','delivered','cancelled','refunded'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select>
<select name="payment_status" class="border border-black/15 bg-white px-3 py-3 text-sm"><option value="">All payments</option>@foreach(['pending','paid','failed','refunded'] as $s)<option value="{{ $s }}" @selected(request('payment_status')===$s)>{{ ucfirst($s) }}</option>@endforeach</select>
<button class="bg-black px-5 py-3 text-xs uppercase tracking-[.16em] text-white">Filter</button></form>
<div class="overflow-x-auto border border-black/10 bg-white"><table class="w-full text-left text-sm"><thead class="border-b border-black/10 bg-black/[.03] text-[10px] uppercase tracking-[.15em] text-black/50"><tr><th class="p-4">Order</th><th class="p-4">Customer</th><th class="p-4">Status</th><th class="p-4">Payment</th><th class="p-4">Items</th><th class="p-4 text-right">Total</th></tr></thead><tbody>@forelse($orders as $order)<tr class="border-b border-black/5 hover:bg-black/[.02]"><td class="p-4"><a class="font-medium underline" href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a><div class="mt-1 text-xs text-black/45">{{ optional($order->placed_at)->format('d M Y H:i') ?: $order->created_at->format('d M Y') }}</div></td><td class="p-4">{{ $order->customer_name ?: optional($order->customer)->full_name }}<div class="text-xs text-black/45">{{ $order->customer_email }}</div></td><td class="p-4 capitalize">{{ $order->status }}</td><td class="p-4 capitalize">{{ $order->payment_status }}</td><td class="p-4">{{ $order->items_count }}</td><td class="p-4 text-right font-medium">{{ $order->currency }} {{ number_format((float)$order->grand_total,2) }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-black/45">No orders found.</td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $orders->links() }}</div>
@endsection
