@extends('admin.layouts.app')
@section('title','Analytics') @section('header','Analytics & Reports') @section('eyebrow','Intelligence / commerce')
@section('content')
<div style="display:flex;align-items:flex-end;justify-content:space-between;gap:14px;flex-wrap:wrap;margin-bottom:18px"><div><h2 style="font-size:27px;margin:0">Analytics & reporting</h2><p class="admin-muted" style="font-size:12px;margin:7px 0 0">Commercial performance for a selected reporting period.</p></div><div style="display:flex;gap:6px"><a class="admin-btn" href="{{ route('admin.analytics.export',['type'=>'orders']) }}">Orders CSV</a><a class="admin-btn" href="{{ route('admin.analytics.export',['type'=>'customers']) }}">Customers CSV</a><a class="admin-btn" href="{{ route('admin.analytics.export',['type'=>'products']) }}">Products CSV</a></div></div>
<form class="admin-card" method="GET" style="display:grid;grid-template-columns:1fr 1fr auto;gap:8px;padding:14px;margin-bottom:14px"><input class="admin-field" type="date" name="date_from" value="{{ request('date_from',$from->toDateString()) }}"><input class="admin-field" type="date" name="date_to" value="{{ request('date_to',$to->toDateString()) }}"><button class="admin-btn">Apply period</button></form>
<div style="display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin-bottom:14px">@foreach([['Revenue','PKR '.number_format($stats['revenue'])],['Orders',$stats['orders']],['New customers',$stats['customers']],['Catalog',$stats['products']],['AOV','PKR '.number_format($stats['aov'])],['Units',$stats['units']]] as [$l,$v])<div class="admin-card" style="padding:15px"><div class="admin-eyebrow">{{ $l }}</div><div style="font-size:20px;font-weight:720;margin-top:7px">{{ $v }}</div></div>@endforeach</div>
<div class="admin-section-grid"><section class="admin-card"><div class="admin-card-header"><div><div class="admin-eyebrow">Top products</div><div style="font-size:14px;font-weight:700;margin-top:4px">Revenue leaders</div></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th style="text-align:right">Units</th><th style="text-align:right">Revenue</th></tr></thead><tbody>@forelse($top as $p)<tr><td style="font-weight:700">{{ $p->product_name }}</td><td style="text-align:right">{{ $p->qty }}</td><td style="text-align:right">PKR {{ number_format((float)$p->revenue) }}</td></tr>@empty<tr><td colspan="3" class="admin-muted" style="padding:40px;text-align:center">No sales data.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-card"><div class="admin-card-header"><div><div class="admin-eyebrow">Order mix</div><div style="font-size:14px;font-weight:700;margin-top:4px">Status distribution</div></div></div><div style="padding:8px 20px">@foreach($statuses as $s)<div class="admin-mini-stat"><span style="font-size:11px;text-transform:capitalize">{{ $s->status }}</span><strong>{{ $s->total }}</strong></div>@endforeach</div></section></div>
<section class="admin-card" style="margin-top:14px"><div class="admin-card-header"><div><div class="admin-eyebrow">Daily performance</div><div style="font-size:14px;font-weight:700;margin-top:4px">{{ $from->format('d M Y') }} — {{ $to->format('d M Y') }}</div></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th style="text-align:right">Orders</th><th style="text-align:right">Revenue</th></tr></thead><tbody>@foreach($daily as $d)<tr><td>{{ \Carbon\Carbon::parse($d->day)->format('d M Y') }}</td><td style="text-align:right">{{ $d->orders_count }}</td><td style="text-align:right">PKR {{ number_format((float)$d->revenue) }}</td></tr>@endforeach</tbody></table></div></section>
<style>@media(max-width:1000px){.admin-page>div:nth-child(3){grid-template-columns:repeat(3,minmax(0,1fr))!important}}@media(max-width:600px){.admin-page>div:nth-child(3){grid-template-columns:1fr 1fr!important}}</style>
@endsection
