@extends('admin.layouts.app')
@section('title',$coupon->exists?'Edit Promotion':'Create Promotion')
@section('header',$coupon->exists?'Edit Promotion':'Create Promotion')
@section('eyebrow','Commerce / promotions')
@section('content')
<form method="POST" action="{{ $coupon->exists?route('admin.coupons.update',$coupon):route('admin.coupons.store') }}">@csrf @if($coupon->exists)@method('PUT')@endif
<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap;margin-bottom:18px"><div><a href="{{ route('admin.coupons.index') }}" class="admin-muted" style="font-size:10px">← Back to promotions</a><h2 style="font-size:27px;margin:7px 0 0">{{ $coupon->exists?$coupon->code:'New promotion' }}</h2></div><button class="admin-btn admin-btn-primary">Save promotion</button></div>
<div style="display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:14px;align-items:start"><section class="admin-card" style="padding:20px"><div class="admin-eyebrow">Offer</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:16px">
<label style="font-size:11px;font-weight:680">Coupon code<input class="admin-field" style="margin-top:7px;text-transform:uppercase" required name="code" value="{{ old('code',$coupon->code) }}"></label>
<label style="font-size:11px;font-weight:680">Campaign name<input class="admin-field" style="margin-top:7px" name="name" value="{{ old('name',$coupon->name) }}"></label>
<label style="font-size:11px;font-weight:680">Discount type<select class="admin-field" style="margin-top:7px" name="type"><option value="percentage" @selected(old('type',$coupon->type)==='percentage')>Percentage</option><option value="fixed" @selected(old('type',$coupon->type)==='fixed')>Fixed amount</option></select></label>
<label style="font-size:11px;font-weight:680">Discount value<input class="admin-field" style="margin-top:7px" required type="number" step=".01" min="0" name="value" value="{{ old('value',$coupon->value) }}"></label>
<label style="font-size:11px;font-weight:680">Minimum order<input class="admin-field" style="margin-top:7px" type="number" step=".01" min="0" name="minimum_order" value="{{ old('minimum_order',$coupon->minimum_order) }}"></label>
<label style="font-size:11px;font-weight:680">Maximum discount<input class="admin-field" style="margin-top:7px" type="number" step=".01" min="0" name="maximum_discount" value="{{ old('maximum_discount',$coupon->maximum_discount) }}"></label>
</div></section>
<aside style="display:grid;gap:14px;position:sticky;top:96px"><section class="admin-card" style="padding:20px"><div class="admin-eyebrow">Limits & schedule</div><div style="display:grid;gap:11px;margin-top:15px"><input class="admin-field" type="number" min="1" name="usage_limit" value="{{ old('usage_limit',$coupon->usage_limit) }}" placeholder="Total usage limit"><input class="admin-field" type="number" min="1" name="usage_limit_per_customer" value="{{ old('usage_limit_per_customer',$coupon->usage_limit_per_customer) }}" placeholder="Per-customer limit"><label style="font-size:10px">Starts<input class="admin-field" style="margin-top:6px" type="datetime-local" name="starts_at" value="{{ old('starts_at',optional($coupon->starts_at)->format('Y-m-d\TH:i')) }}"></label><label style="font-size:10px">Ends<input class="admin-field" style="margin-top:6px" type="datetime-local" name="ends_at" value="{{ old('ends_at',optional($coupon->ends_at)->format('Y-m-d\TH:i')) }}"></label><label style="display:flex;gap:8px;font-size:11px"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$coupon->exists?$coupon->is_active:true))> Enabled</label></div></section>
@if($coupon->exists)<section class="admin-card" style="padding:20px;border-color:#efc4c0"><div class="admin-eyebrow" style="color:#9d2018">Danger zone</div><p class="admin-muted" style="font-size:10px">Deleting removes this coupon definition.</p><button form="delete-promotion" class="admin-btn" style="width:100%;color:#9d2018" data-admin-confirm="Delete this promotion permanently?">Delete promotion</button></section>@endif
</aside></div></form>
@if($coupon->exists)<form hidden id="delete-promotion" method="POST" action="{{ route('admin.coupons.destroy',$coupon) }}">@csrf @method('DELETE')</form>@endif
<style>@media(max-width:850px){form>div:nth-child(2){grid-template-columns:1fr!important}form aside{position:static!important}}</style>
@endsection
