@extends('admin.layouts.app')
@section('title','Promotions')
@section('header','Promotions')
@section('eyebrow','Commerce / incentives')
@section('content')
<div style="display:flex;align-items:flex-end;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:18px"><div><h2 style="font-size:27px;margin:0">Promotions & coupons</h2><p class="admin-muted" style="font-size:12px;margin:7px 0 0">Discount codes, usage limits, schedules and offer governance.</p></div><a href="{{ route('admin.coupons.create') }}" class="admin-btn admin-btn-primary">+ Create promotion</a></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px">@foreach([['All',$summary['all']],['Enabled',$summary['enabled']],['Scheduled',$summary['scheduled']],['Expired',$summary['expired']]] as [$l,$v])<div class="admin-card" style="padding:15px"><div class="admin-eyebrow">{{ $l }}</div><div style="font-size:21px;font-weight:720;margin-top:7px">{{ $v }}</div></div>@endforeach</div>
<section class="admin-card"><form method="GET" style="display:grid;grid-template-columns:1fr 180px auto;gap:8px;padding:14px;border-bottom:1px solid #e4e7ec"><input class="admin-field" name="q" value="{{ request('q') }}" placeholder="Search code or campaign"><select class="admin-field" name="state"><option value="">All states</option><option value="enabled" @selected(request('state')==='enabled')>Enabled</option><option value="disabled" @selected(request('state')==='disabled')>Disabled</option><option value="scheduled" @selected(request('state')==='scheduled')>Scheduled</option><option value="expired" @selected(request('state')==='expired')>Expired</option></select><button class="admin-btn">Filter</button></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Code</th><th>Offer</th><th>Usage</th><th>Schedule</th><th>State</th><th style="text-align:right">Actions</th></tr></thead><tbody>@forelse($coupons as $c)<tr><td><a href="{{ route('admin.coupons.edit',$c) }}" style="font-weight:750">{{ $c->code }}</a><div class="admin-muted" style="font-size:9px;margin-top:4px">{{ $c->name ?: 'No campaign name' }}</div></td><td>{{ $c->type==='percentage'?number_format((float)$c->value,0).'%':'PKR '.number_format((float)$c->value) }}</td><td>{{ $c->used_count }}{{ $c->usage_limit?' / '.$c->usage_limit:'' }}</td><td style="font-size:10px">{{ optional($c->starts_at)->format('d M Y H:i') ?: 'Immediate' }}<br><span class="admin-muted">to {{ optional($c->ends_at)->format('d M Y H:i') ?: 'Open ended' }}</span></td><td><span class="admin-status {{ $c->isCurrentlyValid()?'success':($c->is_active?'warning':'') }}">{{ $c->isCurrentlyValid()?'Live':($c->is_active?'Not live':'Disabled') }}</span></td><td style="text-align:right"><div style="display:flex;justify-content:flex-end;gap:6px"><a class="admin-btn" href="{{ route('admin.coupons.edit',$c) }}">Edit</a><form method="POST" action="{{ route('admin.coupons.toggle',$c) }}">@csrf<button class="admin-btn">{{ $c->is_active?'Disable':'Enable' }}</button></form><form method="POST" action="{{ route('admin.coupons.duplicate',$c) }}">@csrf<button class="admin-btn">Duplicate</button></form></div></td></tr>@empty<tr><td colspan="6" class="admin-muted" style="padding:45px;text-align:center">No promotions found.</td></tr>@endforelse</tbody></table></div></section>
<div style="margin-top:18px">{{ $coupons->links() }}</div>
@endsection
