@extends('admin.layouts.app')
@section('title',$category->exists?'Edit Category':'Create Category') @section('header',$category->exists?'Edit Category':'Create Category') @section('eyebrow','Catalog / taxonomy')
@section('content')
@php($selected = collect(old('product_ids', $category->exists ? App\\Models\\Product::where("category_id", $category->id)->pluck("id")->all() : []))->map(fn($id)=>(int)$id)->all())
<form method="POST" action="{{ $category->exists?route('admin.categories.update',$category):route('admin.categories.store') }}">@csrf @if($category->exists)@method('PUT')@endif
<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap;margin-bottom:18px"><div><a class="admin-muted" style="font-size:10px" href="{{ route('admin.categories.index') }}">← Back</a><h2 style="font-size:27px;margin:7px 0 0">{{ $category->exists?$category->name:'New category' }}</h2></div><button class="admin-btn admin-btn-primary">Save category</button></div>
<div style="display:grid;grid-template-columns:minmax(0,.75fr) minmax(350px,1.25fr);gap:14px;align-items:start"><section class="admin-card" style="padding:20px"><div class="admin-eyebrow">Definition</div><div style="display:grid;gap:12px;margin-top:16px"><label style="font-size:11px;font-weight:680">Name<input class="admin-field" style="margin-top:7px" name="name" required value="{{ old('name',$category->name) }}"></label><label style="font-size:11px;font-weight:680">Slug<input class="admin-field" style="margin-top:7px" name="slug" value="{{ old('slug',$category->slug) }}"></label><label style="font-size:11px;font-weight:680">Description<textarea class="admin-field" style="padding-top:10px;min-height:130px;margin-top:7px" name="description">{{ old('description',$category->description) }}</textarea></label><label style="font-size:11px;font-weight:680">Sort order<input class="admin-field" style="margin-top:7px" type="number" min="0" name="sort_order" value="{{ old('sort_order',$category->sort_order??0) }}"></label><label style="display:flex;gap:8px;font-size:11px"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$category->exists?$category->is_active:true))> Active / visible</label></div></section>
<section class="admin-card"><div class="admin-card-header"><div><div class="admin-eyebrow">Merchandising</div><div style="font-size:14px;font-weight:700;margin-top:4px">Assigned products</div></div><span class="admin-muted" style="font-size:10px">Select any products to include</span></div><div style="padding:12px 20px;max-height:620px;overflow:auto">@foreach($products as $product)<label style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #edf0f3;font-size:11px"><span style="display:flex;align-items:center;gap:9px"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked(in_array($product->id,$selected,true))><strong>{{ $product->name }}</strong></span><span class="admin-status {{ $product->status==='active'?'success':'warning' }}">{{ ucfirst($product->status) }}</span></label>@endforeach</div></section></div></form>
@if($category->exists)<form method="POST" action="{{ route('admin.categories.destroy',$category) }}" style="margin-top:14px">@csrf @method('DELETE')<button class="admin-btn" style="color:#9d2018" data-admin-confirm="Delete this category?">Delete category</button></form>@endif
<style>@media(max-width:850px){form>div:nth-child(2){grid-template-columns:1fr!important}}</style>@endsection
